### PR TITLE
List react-katex in Libraries

### LINKED ISSUE #1155: Is there a React / ES6 implementation?
Hi there,

I'm trying to set up KaTeX in react-16 using ES6. However I can't get it working. Also the react-katex repo is poorly maintained, so I'm currently kind of stuck. How to integrate katex rendering into react-16?

### PR DESCRIPTION
**Pull request by dudko**
Hello Khaners,

as one of the contributors of `react-katex`, React components that use KaTeX to typeset math expressions, I would like to you to list `react-katex` in your Libraries listing.

Thank you!

(fix #1155)

### CODE REVIEW

**Comment by dudko** [comment]
[clabot:check]

**Comment by edemaine** [comment]
@dudko Thanks for the PR!  Have you read our issue #1155?  There were some issues with react-katex reported there, though perhaps they've all been addressed by now.  Also it sounds like react-latex is a competitor that might also be worth mentioning.  What do you think is best?

**Comment by dudko** [comment]
@edemaine , thank you for your quick response. I've encountered mentioned issues with `react-katex` in past. Code base got outdated and incompatible with new react releases. I did contribute to the project recently and hopefully resolved all those issues.

Regardless of `react-latex`, it does pretty much the same job as `react-katex`. Both packages are definitely worth mentioning. It's only on users to decide which one is better. :)

**Comment by edemaine** [comment]
Awesome! My only suggestion would be to put React above Ruby, for capitalization and prominence. But also fine as is.

**Pull request merged**
