### PR TITLE
Add 0.08em padding above \sqrt

### PR DESCRIPTION
**Pull request by ronkok**
This way, any browser imprecision on the parent span.height will not encroach on the ink of the \sqrt top line.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
I'll regenerate the screenshots this weekend.

**Comment by kevinbarabash** [comment]
Swiping the Raisebox screenshots shows that the surd has come down a bit, but using texcmp it looks like it's closer to what LaTeX.
raisebox

**Comment by kevinbarabash** [comment]
@ronkok I'm happy with how things are looking in Firefox when the font is 12px.  I'm not seeing any of the clipping I was seeing before.  I generated the screenshots before you merged in master so I will have to regenerate them.

**Comment by kevinbarabash** [comment]
Hmm... I tried regenerating the screenshots in question based on `32682b4`, but there's no change.  Maybe merge with `master` again.

**Comment by ronkok** [comment]
I tried another merge here, too. I'm getting messages about multiple image file conflicts. I'm sorry about this, but I really don't know what to do next.

**Comment by kevinbarabash** [comment]
@ronkok to resolve conflicts in binary files use `git checkout --ours -- path_to_file` or `git checkout --theirs -- path_to_file`.  In this case it doesn't matter which one you pick b/c I'm going to regenerate the screenshots.  See https://stackoverflow.com/questions/278081/resolving-a-git-conflict-with-binary-files.

**Comment by ronkok** [comment]
Closing here. Will reopen elsewhere.

**Pull request closed without merging**
