### PR TITLE
Cleanup domTree.js to re-use code

### PR DESCRIPTION
**Pull request by edemaine**
* Refactor `span` and `anchor` into common `HtmlDomContainer` superclass, without changing internal data structure (e.g. not storing `tagName`).
* Makes it easy to add more similar tags
* Number of lines falls from 676 to 587

My motivation for doing this is that I'd like to try reimplementing `array` in terms of `table`, `tr`, `td`, which requires several new tags similar to `span` but with a different `tagName`.  This will make that work much easier.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@edemaine it's like you read my mind.  I was thinking of this exact thing when reading through #1287.

**Comment by ylemkimon** [comment]
I should've checked how much polyfill this generates. I think this PR need to be reverted.

**Comment by edemaine** [comment]
@ylemkimon Is it a lot? Maybe we can avoid it somehow?

**Comment by ylemkimon** [comment]
@edemaine It it self is about 50KB. I think we should avoid using class inheritance until our target browsers natively support it. I've created a PR to use helper functions in #1469.

**Comment by kevinbarabash** [comment]
babel has a `loose` mode setting for some transforms.  We could also investigate that.

**Comment by ylemkimon** [comment]
@kevinbarabash #1469 enables the loose mode. However, Babel's loose inheritance is still expensive.

**Pull request merged**
