### PR TITLE
bump version number to v0.2.0 in cdn url

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by xymostech** [comment]
Hi, this is great! Thanks for sending it in. Can you sign the Khan Academy CLA so I can merge it in? http://www.khanacademy.org/r/cla

**Comment by PeterDaveHello** [comment]
Sure.

**Comment by PeterDaveHello** [comment]
Done.

**Comment by xymostech** [comment]
Thanks!

**Pull request merged**
