### PR TITLE
v0.10.0 release

### LINKED ISSUE #1544: Release 0.10.0
I was thinking with all of the changes to our docs that I should probably publish to gh-pages again.  Does anyone have any concerns about that?

### PR DESCRIPTION
**Pull request by ylemkimon**
Closes #1544.

* Fix multiple occurring hash replacement

Sorry this took so long. As @edemaine said in https://github.com/Khan/KaTeX/issues/1544#issuecomment-429547721, I think it's better to fix bugs later, if any.

### CODE REVIEW

**Comment by ylemkimon** [comment]
TODO: update docusaurus

**Comment by edemaine** [comment]
TODO (?): Update CHANGELOG.md

**Comment by ylemkimon** [comment]
@edemaine I've updated the changelog and drafted the release note at https://github.com/Khan/KaTeX/releases/tag/untagged-3def5a271b493609f63d. (I'm not sure it's visible to other maintainers.)

**Comment by edemaine** [comment]
I thought that the GitHub release notes would just list the changes since the last version (release candidate) -- at least that's what we've been doing before.  I could see and edit the draft (visible here: https://github.com/Khan/KaTeX/releases/), and wrapped a couple of commands that needed wrapping in backticks. (It might be worth doing this for all LaTeX commands, also in the change log?)

**Comment by ylemkimon** [comment]
@edemaine What do you think about:
```markdown
### Added
- Unicode ⟦⟧ (#1750)
- KaTeX website & documentation (#1571, #1642, #1680, #1683, #1688, #1631, #1727)
- Browserslist (#1662)
- 6-digit color without # (#1690)
- \mathnormal (#1700)
- \lparen and \rparen (#1741)

### Changed
- Port to @flow: CssStyle (#1684)
- Improve screenshotter (#1644, #1643)
- Improve release script (#1660, #1665)
- Refactor buildCommon (#1633, #1640)
- Upgrade to Babel 7 (#1595)
- Refactor Parser (#1711, #1723)

### Fixed
- Remove duplicate defineFunction invocation for \mathop (#1701)
- Fix tag positioning to live within katex-html parent (#1721)
- Fix `\mathit` font and italic correction (#1700)
```
?

**Comment by kevinbarabash** [comment]
The 0.10.0 docs look off because 
https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css is missing.  Is that because https://github.com/Khan/KaTeX/releases/tag/untagged-11f04a3ba859daa27977 is still in draft?

**Comment by ylemkimon** [comment]
@kevinbarabash It's because it's not published to the NPM. The CDN depends on the NPM.

**Comment by kevinbarabash** [comment]
I'm curious about the order of operations.  If we deploy this then the docs will temporarily be broken until we do the publish.  On the flip-side, if we do the publish first then we have to do this release before anything else gets landed on `master`... or do as a branch from the publish commit.

**Comment by kevinbarabash** [comment]
I was confused by https://github.com/Khan/KaTeX/releases/tag/untagged-11f04a3ba859daa27977 b/c I thought 0.10.0 had already been published but looking more closely I can see that no commit has been tagged in that draft release yet.

**Pull request merged**
