### PR TITLE
Fix color support for stretchy, strikethrough, and fbox

### PR DESCRIPTION
**Pull request by xsznix**
Summary:
Stuff like `\red{\overbrace{AB}}` works now in addition to `\color{red}{\overbrace{AB}}`. Strikethrough now respects color. The Firefox in the screenshotter doesn't seem to support `background-image` + `mask`, but I manually tested that the latest Firefox does.

Test plan:
Ran `make`, then tested in latest Chrome and Firefox to ensure color support was working, then ran `make screenshots`.

### CODE REVIEW

**Comment by ronkok** [comment]
Interesting. I did not realize that KaTeX supported that syntax. It does, though. `\red{A}` renders a red A.

Are there any LaTeX packages that support this syntax?

**Comment by edemaine** [comment]
Nor did I!  [Here's the code](https://github.com/Khan/KaTeX/blob/master/src/functions.js#L352-L378).  And I guess there are matching `katex-...` colors in the CSS.  I'm not aware of a LaTeX package implementing this -- probably a KA thing. IMO, these might make more sense as macros...

**Comment by ronkok** [comment]
Ah, I see. Well, @xymostech has written issue #28, which states that these custom colors were meant to be KA-only and not available for everyone. There is some push back in the discussion.

I suppose one approach would be to accept this PR, so that KaTeX has consistent behavior. Then, if a PR is ever written to resolve #28, it would have to address the whole issue.

**Comment by spicyj** [comment]
Yes, the intent was always to move those to macros as soon as was possible.

I think this change seems pretty unambiguously good especially in the existing presence of the options.getColor method although I don't understand the significance of the CSS change.

**Comment by ronkok** [comment]
The CSS change fixes a bug which has crept into function `stretchy.encloseSpan()`. At one time, I pushed `mask` onto the list of classes for the relevant span. Somehow, I let that item slip out. The CSS in this PR corrects for my error.

Thank you, @xsznix! 

Also, Firefox 53 was the first Firefox release with full `mask` support. I suppose Screenshotter is using an older version.

**Comment by edemaine** [comment]
In this case, perhaps we should accept this PR and then make a new one to rewrite `\red` etc. in terms of macros?  I could use some clarification on whether those macros belong in KaTeX (e.g. for backwards compatibility) or in another KA project.

**Comment by kevinbarabash** [comment]
> In this case, perhaps we should accept this PR and then make a new one to rewrite \red etc. in terms of macros? 

I think that makes sense.

> I could use some clarification on whether those macros belong in KaTeX (e.g. for backwards compatibility) or in another KA project.

As per the comments in #28, we definitely want to move KA custom colors out of KaTeX but in a thoughtful way.

**Comment by kevinbarabash** [comment]
@xsznix thanks for the PR.  @edemaine thanks for reviewing.

**Pull request merged**
