### PR TITLE
Lint .less files with stylelint

### PR DESCRIPTION
**Pull request by edemaine**
In particular, prevent tabs, fixing #921.

### CODE REVIEW

**Comment by rrandallcainc** [comment]
Should node_modules be added as an ignore in the flowconfig?

**Comment by edemaine** [comment]
@rrandallcainc I don't think so? Wouldn't it be good to test typing across all available modules?

Anyway, not sure that's relevant to this particular PR.

**Comment by rrandallcainc** [comment]
It looks like the new stylelint is causing the build to fail here when running flow. Perhaps a simple solution would be to add an ignore for stylelint for now?

Looks like an open thread on this issue here: https://github.com/stylelint/stylelint/issues/2322

**Comment by edemaine** [comment]
Oops, sorry @rrandallcainc, now I see what you mean!  (I was looking at the Github post on my phone, which isn't the best interface, and didn't see the failed checks.)

As suggested in one of those threads, I added a link to `node_modules/stylelint/decls` to the `libs` section of `.flowconfig` and now it seems to work.

**Pull request merged**
