### PR TITLE
Add quick syntax guide to README.md

### PR DESCRIPTION
**Pull request by dt1973**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
I'd like it more if there was something that said, "Hey! Not all of MathJax is supported!"

**Comment by kevinb7** [comment]
It would be better to link to https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX so that people know what's supported and what isn't.  Also, stating that "KaTeX uses MathJax syntax" is a little weird.  It would be more precise to say that KaTeX uses TeX syntax, but I feel like that's already covered in the first line of the README which states: "KaTeX is a ... library for TeX math rendering"

**Comment by kevinb7** [comment]
I added a link to the wiki page with the list of commands.  If people are looking for information on syntax then we could link to some `TeX` and/or `LaTeX` resources.

**Comment by kevinbarabash** [comment]
I'm closing this b/c I think it's been addressed.  @dt1973 please reopen if you think we should add more information to the README.md.

**Pull request closed without merging**
