### PR TITLE
package non minified versions to simplify debugging

### PR DESCRIPTION
**Pull request by tokiloki**

### CODE REVIEW

**Comment by kevinb7** [comment]
@tokiloki are you running into any issues in particular?

**Comment by tokiloki** [comment]
Kevin, I was getting some error on released version then I switched to github version and now I tried can not reproduce it on release version) Maybe we do not need this request in this case)

**Comment by kevinb7** [comment]
I'm going to close this for now.

**Comment by kevinb7** [comment]
I'm going to close this for now.  Please re-open if you run into issues that require debugging the source.

**Pull request closed without merging**
