### PR TITLE
Specify height for SVG elements

### PR DESCRIPTION
**Pull request by ian-r-rose**
I ran into an issue where a low-specificity CSS rule elsewhere on the page was overriding the KaTeX SVG height, rendering fraction lines invisible. Does this seem like a reasonable addition to the style sheet?

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Ah, I see this is also related to #1249 and #1173. Feel free to close if this is not the direction you want to go.

**Comment by ronkok** [comment]
I don't see how this PR could hurt. SVG `height` is normally set in each instance of an inline SVG. The exception, frac-lines, will no longer use SVGs if/when PR #1249 is merged. So I think this PR will have no effect. But again, it doesn't hurt.

**Comment by ian-r-rose** [comment]
Here is a small example demonstrating the problem: a low-specificity, seemingly innocuous CSS rule will interfere with fraction line rendering:
```html
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"></script>
<style>
  svg {
    height: auto;
  }
  .example {
    font-size: 30px;
    text-align: center;
    margin: 30px 0;
  }
</style>
<body>

  <div class="example tex" data-expr="\frac{a}{b}">
  </div>

<script>
  window.onload = function() {
      var tex = document.getElementsByClassName("tex");
      Array.prototype.forEach.call(tex, function(el) {
          katex.render(el.getAttribute("data-expr"), el);
      });
  };
</script>
```

**Comment by ronkok** [comment]
I can confirm both the diagnosis and the proposed solution. And it applies to more than just frac-lines. Other SVGs, like `\sqrt`, have the same behavior. 

So I retract my earlier comment and I very much endorse this PR.  Thank you, @ian-r-rose.

**Pull request merged**
