### PR TITLE
Adding support for SansSerif Bold and Italic Fonts

### PR DESCRIPTION
**Pull request by rrandallcainc**
I'm not sure why SansSerif Bold/Italic were left out of the fontMetrics. Perhaps there's a good reason that I don't know.

I thought I'd open this PR, just incase it was overlooked.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@rrandallcainc is there any way to actually render SansSerif-Bold?  It seems like we'll have to fix #676 before we can test this PR.

**Comment by rrandallcainc** [comment]
@kevinbarabash You're right, this PR doesn't serve much use until 676 is merged. I figured this was out of the scope of 676, so I thought I would open a separate PR. 

I intend on working on 676 some point this week.

In the meantime, is there something you'd want me to add to this PR to indicate it's dependent on 676?

**Comment by rrandallcainc** [comment]
Updated to include SansSerif Italic as well.

**Comment by kevinbarabash** [comment]
> In the meantime, is there something you'd want me to add to this PR to indicate it's dependent on 676

You could update your initial comment to indicate that.  Also, using #676 instead 676 will create a link to the issue making it easier for people to navigate to.

**Comment by kevinbarabash** [comment]
I wish github had a better way to indicate dependencies.

**Comment by rrandallcainc** [comment]
Closing, as the work is now part of: https://github.com/Khan/KaTeX/pull/944

**Pull request closed without merging**
