### PR TITLE
Fix #534: Teach getTypeOfGroup about font groups.

### LINKED ISSUE #534: \mathbf with subscripts/superscripts causes incorrect spacing
```
\[ A*B+C-D = E \]
\[ A_1 * B^2 + C_3^4 + D^5_6 = E_0 \]
\[ \mathbf{A}*\mathbf{B}+\mathbf{C}-\mathbf{D} = \mathbf{E} \]
\[ \mathbf{A}_1 * \mathbf{B}^2 + \mathbf{C}_3^4 + \mathbf{D}^5_6 = \mathbf{E}_0 \]
```

KaTeX on Chrome 52.0.2743.116 m:

image

MathJax on Chrome 52.0.2743.116 m:

image

### PR DESCRIPTION
**Pull request by kohler**
The type of a font group is the type of its body. This teaches KaTeX that
a span created for a font group, such as for `\mathbf{X}^2`, has the same
type as the underlying group.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@kohler thanks for the PR.  Can you check if this fixes https://github.com/Khan/KaTeX/issues/533 as well?  Also, could you add a screenshot test for this?

**Comment by kohler** [comment]
#533 is a different problem and requires a different fix. This PR has been updated with that fix.

**Comment by kohler** [comment]
Sorry @kevinbarabash Trying to fix/add tests—I’m no Docker expert. On my Mac with newly-installed Docker for Mac, `dockers/Screenshotter/screenshotter.sh --verify` seems to just hang. Should I expect that?

**Comment by kevinbarabash** [comment]
@kohler can you post what you're seeing the console?

**Comment by kohler** [comment]
Docker for Mac doesn't support networking in the usual way, apparently. There’s some stuff on their website about it. I had to supply both `--selenium-ip` and `--katex-ip` arguments, rather than/in addition to `--container`.

The current PR is failing two screenshot tests, LimitControls and SupSubLeftAlignReset. But I think the PR’s output is better: the older output (in blue) had less space than it should; the newer output (in red) restores the space, and looks visually closer to the output of straight TeX.

If you agree, I’ll update these screenshot tests and add some new ones.

limitcontrols-diff
supsubleftalignreset-diff

**Comment by gagern** [comment]
> Docker for Mac doesn't support networking in the usual way, apparently.

Yay, yet another way to install Docker, after I got docker-machine to work for me in #494. Makes me wonder whether I should try to come to terms with this, or whether I should just wait to see what approach they use next month.

> There’s some stuff on their website about it.

I guess you mean [Networking features in Docker for Mac](https://docs.docker.com/docker-for-mac/networking/).

> I had to supply both `--selenium-ip` and `--katex-ip` arguments, rather than/in addition to `--container`.

Did you add another IP address to your loopback device, as suggested by these documents? If not, what did you use for the `--katex-ip` and how did you find it?

I'm currently thinking about how to auto-detect this situation, and handle it with less need for user intervention.

**Comment by kohler** [comment]
> I guess you mean Networking features in Docker for Mac.

Yep!

> Did you add another IP address to your loopback device, as suggested by these documents? If not, what did you use for the `--katex-ip` and how did you find it?

I tried the IP network alias suggested by that document, choosing the 172.17/16 network suggested by the screenshotter’s Docker config parsing. It didn’t work, so I just supplied my host’s local IP, found by `ifconfig en0`. This required some changes to screenshotter.js—included in this PR—so that `--katex-ip` is obeyed even in the presence of `--container`.

**Comment by kohler** [comment]
I’m also testing a fix for #541. This fix involves making `.mspace` nodes their own class, rather than examples of `.mord`. TeX glues aren’t atoms.

The combination of that fix and this PR restores the original SupSubLeftAlignReset screenshotter test behavior.

How to move forward? Would you prefer separate fixes for all these, plus a PR for the screenshotter changes?

@kevinbarabash

**Comment by gagern** [comment]
Personally I'd say the screenshotter is something semantically distinct, so that should be a separate PR. If the effects of the other two really cancel out completely, then having a single PR with two commits might be nice, to see that it really remains unmodified. In that case, it would be nice to rebase the branch so that it has two commits for the two distinct changes. But that may wait till after review. And if the image just looks mostly the same, but not pixel-exact, then I'd go for two PRs there as well.

**Comment by kohler** [comment]
Closing this in favor of a new PR, #567.

**Pull request closed without merging**
