### PR TITLE
A WIP patch toward making characters like å display correctly in text mode

### PR DESCRIPTION
**Pull request by davidflanagan**
See Issue #1066 for more details.

Note that this patch breaks some tests that will need to be fixed.

### CODE REVIEW

**Comment by davidflanagan** [comment]
This is what I had in mind for fixing issue #1066

**Comment by davidflanagan** [comment]
@kevinbarabash  and @edemaine what do you think? This approach is somewhat at odds with https://github.com/Khan/KaTeX/pull/1069 which supports the decomposed approach to accented forms in text mode. 

I'm not sure what LaTeX approach to Unicode is: do we embrace codepoints like å and allow them to display as single glyphs while also retaining support for pre-Unicode things like \aa?

**Comment by kevinbarabash** [comment]
@davidflanagan this is what we used to do.  Unfortunately, it results in the wrong font being used for latin characters with accents.  Even though the font contains the base character and the accent, the browser doesn't know to render those together.  All it knows is that the glyph for `å` doesn't exist in the font and so it falls back to another font which does have the glyph.  The results in the following rendering for `\text{aå}` which is not what we want:
screen shot 2018-01-24 at 10 48 34 am

**Comment by kevinbarabash** [comment]
Closing in preference of #1094.

**Pull request closed without merging**
