### PR TITLE
Adds Bower manifest.

### PR DESCRIPTION
**Pull request by jmeas**
This adds a [bower](http://bower.io/) file, if you're interested in supporting Bower. If you are then [you'll want to run](http://bower.io/docs/creating-packages/#register)

```
bower register katex https://github.com/Khan/KaTeX
```

after merging this.

*Note: I already signed the CLA*

### CODE REVIEW

**Comment by joelkuiper** [comment]
:+1:

**Comment by shime** [comment]
:+1:

**Comment by fibo** [comment]
Can you please merge this?
It would be great, then I will try KaTex and update my article [Math on GitHub Pages](http://g14n.info/2014/09/math-on-github-pages/).

**Comment by kevinb7** [comment]
We have a bower.json file now, see https://github.com/Khan/KaTeX/commit/2060ebaf214739cda866368175185c5151b86426.

**Comment by kevinb7** [comment]
You can now use ```bower install katex``` to grab the built files.  

@jmeas Sorry for forgetting about this pull request.

**Comment by fibo** [comment]
Thank you,

I just noticed that package.json and bower.json files has version 0.3.0, while last tag is 0.4.0.

Bower will work, but, with a warning.

**Pull request closed without merging**
