### PR TITLE
Change frac-line from SVG line to SVG path

### PR DESCRIPTION
**Pull request by ronkok**
SVG paths have given us more predictable behavior than SVG lines.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
I missed `Array` sorry about that.

**Comment by kevinbarabash** [comment]
The recent merge of #1078 has cause the conflicts.  Can you merge `master` and the I'll regenerate the screenshots again.

**Comment by ronkok** [comment]
I tried another merge. Keeping my fingers crossed.

**Comment by ronkok** [comment]
That last merge may not have worked. I got a local message that says, "Cannot merge binary files: test/screenshotter/images/ExtensibleArrows-chrome.png".

**Comment by ronkok** [comment]
Closing here. Will reopen elsewhere.

**Pull request closed without merging**
