### PR TITLE
Add CHANGELOG

### PR DESCRIPTION
**Pull request by Kully**
Re: https://github.com/Khan/KaTeX/issues/785

### CODE REVIEW

**Comment by ylemkimon** [comment]
I'm personally against changelogs auto-generated from commit logs and/or merged pull requests.

From [keepachangelog.com](keepachangelog.com):
> Can changelogs be bad?
Yes. Here are a few ways they can be less than useful.
Commit log diffs
Using commit log diffs as changelogs is a bad idea: they're full of noise. Things like merge commits, commits with obscure titles, documentation changes, etc.
The purpose of a commit is to document a step in the evolution of the source code. Some projects clean up commits, some don't.
The purpose of a changelog entry is to document the noteworthy difference, often across multiple commits, to communicate them clearly to end users.

**Comment by Kully** [comment]
> I'm personally against changelogs auto-generated from commit logs and/or merged pull requests.

I did not autogenerate this, but I agree with the implication that the current CHANGELOG is too cluttered/needs to be more readable by a user.

**Comment by Kully** [comment]
closing for now

**Comment by kevinbarabash** [comment]
A CHANGELOG that simply aggregates the list of bug fixes, new features, and misc from each release in https://github.com/khan/KaTeX/releases might address the concerns about a cluttered change log.

**Comment by edemaine** [comment]
Agreed. I'm unclear on best practices here. Most often I see a CHANGELOG but no Github release notes. Given that we have the latter, do we need the former?

**Comment by kevinbarabash** [comment]
> Given that we have the latter, do we need the former?

The nice thing about the former is that you can see them all together whereas the releases are paginated which isn't that bad imo.

**Comment by Kully** [comment]
> The nice thing about the former is that you can see them all together whereas the releases are paginated which isn't that bad imo.

Plotly's Changelog has sections in each release that work well: Added, Fixed, Updated https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md

@kevinbarabash 
An alternative to just one-paging the release info is picking the relevant notes and categorizing based on these 3 sections, or to just organize them all under these sections. WDYT?

**Comment by ylemkimon** [comment]
They seem to follow [keepachangelog.com](https://keepachangelog.com/en/1.0.0/):
> `Added` for new features.
`Changed` for changes in existing functionality.
`Deprecated` for soon-to-be removed features.
`Removed` for now removed features.
`Fixed` for any bug fixes.
`Security` in case of vulnerabilities.

**Comment by kevinbarabash** [comment]
@Kully the CHANGELOG.md file you linked to looks alright.  I like the categories that @ylemkimon posted to.  Currently the release notes combine `Added` and `Changed` into a single `New Features`.  I kind of like separate them out though.  I guess every once in a while we do have `Breaking Changes` which is kind of like `Changed`.  I'm not sure what would fit into `Changed` but not `Breaking Changes`.  🤔

**Comment by Kully** [comment]
> @Kully the CHANGELOG.md file you linked to looks alright. Should I continue with it then? I deleted the branch because you closed the original issue. I can make the CHANGELOG and split `Nee Features` into `Added` and `Changed` as best I can.

And regarding `Breaking Changes`, I imagine its any change to the code in which functions do not work/raise errors, eg. if `\sqrt{}` no longer worked. This seems like it would be a very small category. And `Changes` would be things like interpolating the sqrt symbol: https://github.com/Khan/KaTeX/issues/1132

What do you think?

**Comment by kevinbarabash** [comment]
I see, so changes might be something like "we made this existing feature better in some way"?

**Comment by Kully** [comment]
@kevinbarabash Yeah exactly. At Plotly that's how we interpret it

**Pull request closed without merging**
