### PR TITLE
Don't inherit SVG style properties from the environment.

### PR DESCRIPTION
**Pull request by davidflanagan**
We don't want to inherit styles that affect SVG painting unless those
styles also affect regular text rendering. This patch adds styles
to the stylesheet so that every svg element in KaTeX output starts
off with a known set of basic fill and stroke attributes.

This should resolve issue #1088

### CODE REVIEW

**Comment by davidflanagan** [comment]
Okay, still need to make tests pass, but I'm hoping that the fix can be basically as simple as this.

**Comment by kevinbarabash** [comment]
@davidflanagan maybe add a screenshot test for this.  It should be possible using the `pre` and `post` properties in `ss_data.yaml` to construct a container with styles that would affect the rendering without your changes.  Something like:
```
SvgReset:
    pre: <div style="fill-opacity: 0.5; stroke-width: 3, ...">
    tex: \sqrt{x+1}
    post: </div>
```

**Comment by davidflanagan** [comment]
That's a great idea, Kevin. I'll do it.

**Comment by davidflanagan** [comment]
Actually, the pre and post attributes on the screenshot tests set the content of spans before and after the math, but they're both siblings of the math element, not ancestors, so I can't use them to set styles that would affect the math...

**Pull request merged**
