### PR TITLE
Allow only allowed protocols in \href

### PR DESCRIPTION
**Pull request by ylemkimon**
* Added `allowedProtocols` settings

### CODE REVIEW

**Comment by ylemkimon** [comment]
@edemaine Thank you for the review! I've added boolean argument to allow or disallow all protocols. I'm not sure about the function.

**Comment by kevinbarabash** [comment]
One alternative solution might be to allow `[ "*" ]` to represent all protocols.  This is going to get more interesting if we ever support embedding images.

**Comment by edemaine** [comment]
@kevinbarabash That might be considered more standard. I could go either way. @ylemkimon Thoughts?

**Comment by ylemkimon** [comment]
I think `["*"]` is more consistent. Changed to `["*"]`.

**Comment by edemaine** [comment]
Looks great!

**Comment by ylemkimon** [comment]
I wonder this qualifies as a security vulnerability.

**Comment by edemaine** [comment]
Maybe, given that `javascript:` was allowed before?  How do we indicate this?

**Comment by kevinbarabash** [comment]
We can add a `security` section in the release notes of the next release.  This is technically a change in behaviour so we should probably go to 0.11.0.

**Pull request merged**
