### PR TITLE
Added \forall, \exists, \nexists, \implies, \iff, and \span

### PR DESCRIPTION
**Pull request by rguthrie3**
Added these symbols and tested.  I will continue to add symbols as I think of them, but I went ahead and submitted a pull request because these symbols (with the exception of span) are very important and they don't seem to be present.

### CODE REVIEW

**Comment by spelufo** [comment]
I think `\implies` also goes by `\then`, but perhaps there is some subte difference.

**Comment by spicyj** [comment]
Thanks for sending this in. These should all be in master now except \implies and \iff which we'll add soon.

**Comment by spicyj** [comment]
Actually, I'm going to close this out but we have #190 now to track those two.

**Comment by correnson** [comment]
Great job ! Although, it would be nice to update the Wiki accordingly, since this is the primary document found when using GitBook, which could be a _great_ environment for co-authoring math. And having logic connectors is a _strong_ requirement here.

**Comment by kevinbarabash** [comment]
@correnson which part of the wiki needs to be updated?

**Comment by correnson** [comment]
https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX

**Comment by kevinbarabash** [comment]
I see, we're missing \forall, \exists, \nexists, and \span.  Good catch.

**Comment by kevinbarabash** [comment]
After double checking it appears that `\span` is not in master.

**Comment by kevinbarabash** [comment]
@correnson I've updated the wiki.

**Comment by correnson** [comment]
Nice!

**Pull request closed without merging**
