### PR TITLE
Improve font metrics creation

### LINKED ISSUE #288: replace fontforge with freetype-py or fonttools
We only use fontforge to extract font metrics, but it's big and requires extra dependencies like XQuartz on Mac OS X.  I found installing fontforge on Mac OS X difficult because it was compiled with a different version of Python so I had to install that version of Python alongside the official one and change one of the scripts to use that version.  

freetype-py on the other hand is smaller and easier to install.  I ran the following two commands and was up and running in minutes:
- brew install freetype
- pip install freetype-py

It's also pretty easy to use:
```
import freetype
face = freetype.Face("static/fonts/KaTeX_Main-Regular.ttf")
face.load_char('S')
print face.glyph.metrics.horiAdvance
...
```
This should make it easier for people who want to add even more font commands after https://github.com/Khan/KaTeX/issues/132 lands like ```\mathsfbf```, etc. or use alternative fonts like AMS Euler or STIX as requested in https://github.com/Khan/KaTeX/issues/123.

### PR DESCRIPTION
**Pull request by gagern**
This is a huge request of various things regarding font metrics creation. I think it is best if you review this one commit at a time, since each commit is a more or less self-contained step in that chain of changes.

* @1f8610cebe2c99223db4082a834fb814afd2b697 solves a build problem if the `python` binary on the `PATH` is Python 3.
* @c20f06da510b228c0a83b6fdb561534581181cea and @ae24b8a4665f9f32659cba9485cc608a3086b17a reformat the metrics data according to #301.
* @8be3b579c009a27ae941d7ec283b1aa85341cc8d fixes a bug I found along the way; here you have to verify some glyphs, comparing TTF content against [these charts](http://www.math.union.edu/~dpvc/jsmath/symbols/welcome.html). Discussion about this happened on #288.
* @db7e46d8c235b3e5ad0c8e271813469bc2e12983 resolves #288 by switching from [fontforge](https://fontforge.github.io/) to [fonttools](https://github.com/behdad/fonttools).

I know you prefer distinct pull requests for distinct issues, but I want to get this out of my head for now, and I think the history will benefit from having a direct relationship between these commits. So please accept my suggestion of reviewing one commit at a time. If at some point you decide that things up to a certain point make sense, and you don't have time to review past that or even decide against later commits, feel free to merge parts of this earlier.

### CODE REVIEW

**Comment by gagern** [comment]
I'll commit modifications to existing commits as squashes and fixups, so that once you're satisfied, I can `git rebase -i --autosquash` everything to keep the logical units intact.

**Comment by kevinb7** [comment]
It looks good.  I have an appointment soon so I'll have another look this afternoon in case I missed something, but I don't foresee any big changes here.

**Comment by kevinb7** [comment]
@gagern other than a few minor changes it looks good.

**Comment by xymostech** [comment]
This looks great! Thanks for this! All of this infrastructure was set up in the week before release, and hasn't been really touched since. :) 

Also, I actually think that it makes more sense to leave all of these commits separate, since they're all self-contained, and they make it easier to figure out what changed. Squashing commits makes sense if you break things and then fix them later (because then doing a git bisect might land you in a broken state) but these all seem fine to merge in. (But maybe the last commit could be merged into the second one, which is something you can do with rebase -i?)

**Comment by gagern** [comment]
> But maybe the last commit could be merged into the second one, which is something you can do with rebase -i?

Even better with `git rebase -i --autosquash`, as [I already said](https://github.com/Khan/KaTeX/pull/303#issuecomment-120048942). I'll wait on a decision about my most recent fixup, whether that should be included or not (discussion [here](https://github.com/gagern/KaTeX/commit/8be3b579c009a27ae941d7ec283b1aa85341cc8d#comments) or on that commit), and if that's resolved I'll rebase and you can merge, right?

**Comment by kevinb7** [comment]
@gagern thanks for the fixup and comments.  Autosquash the fixups and I'll merge the commits.

**Comment by kevinb7** [comment]
@gagern for some reason github isn't notifying me when commits change.  Can you post a quick message when things are ready to merge after rebasing?

**Comment by gagern** [comment]
@kevinb7 Sure, I can do that. Thanks for merging!

**Comment by kevinb7** [comment]
Thanks, and thanks for the pull request.

**Comment by spicyj** [comment]
Yes, GitHub doesn't notify when PRs are updated. It sucks.

**Pull request merged**
