### PR TITLE
webpack server: add disableHostCheck option

### PR DESCRIPTION
**Pull request by edemaine**
Allow server to be accessed from anywhere, which is useful for testing (see #911).  This potentially reveals the source code to the world, but this should not be a concern for testing open-source software.

### CODE REVIEW

**Comment by rrandallcainc** [comment]
@edemaine @kevinbarabash Would you like me to go ahead and merge this?

**Comment by edemaine** [comment]
Thanks @rrandallcainc for the instant review.  Somehow, last I checked, I still couldn't merge, but no problem now.  Thanks for the reminder!

**Comment by edemaine** [comment]
@ylemkimon I believe the recent webpack revamp PRs have disabled this functionality.  Could we add it back?

**Comment by ylemkimon** [comment]
@edemaine We still `disableHostCheck = true`, however it seems that webpack-dev-server CLI has `localhost` as default value for `host`. I'll send a PR setting host to `0.0.0.0`, and meanwhile you can do `npm start -- --host 0.0.0.0`.

**Comment by edemaine** [comment]
#1122 fixed this. Thanks @ylemkimon!

**Pull request merged**
