### PR TITLE
Deploy website

### PR DESCRIPTION
**Pull request by ylemkimon**
Deploy website version based on v0.10.0-rc

### CODE REVIEW

**Comment by edemaine** [comment]
Maybe @ylemkimon could write a document about the release process. 😄 

I just took a quick look at a checkout of this, and the page seems good. (In particular, the CDN is working.)

**Comment by kevinbarabash** [comment]
The website looks great! 🎉

**Comment by ylemkimon** [comment]
Sorry for late responses. I'm not sure it's a GitHub issue or my ISP issue, but GitHub is currently very slow.

> I wonder if there's some way to tell circleci and netlify to ignore PRs against `gh-pages`.

There seems to be no way for Netlify to ignore it. For CircleCI, we can use dummy config or it seems that master branch configuration can be used to control it.

> What command did you run to generate this PR?

I ran `./release.sh -p 0.10.0-rc`, but as `gh-pages` is a protected branch (#1412), I had to push to another branch and open a PR.

> Maybe @ylemkimon could write a document about the release process.

Really I should 😄

**Comment by kevinbarabash** [comment]
Now that we're reviewing the documentation changes in PRs to `master` we probably don't need `gh-pages` to be a protected branch anymore.

**Comment by kevinbarabash** [comment]
`gh-pages` is no longer a protected branch.

**Comment by ylemkimon** [comment]
@kevinbarabash I'm worried that someone may gain access to an account with write access and push malicious code.

**Comment by kevinbarabash** [comment]
Good point.  `gh-pages` is now a protected branch.

**Pull request merged**
