### PR TITLE
Support \oiint and \oiiint

### LINKED ISSUE #392: Support for \oiint
Are there any plans to support \oiint ?

### PR DESCRIPTION
**Pull request by ronkok**
This PR supports \oiint and \oiiint by overlaying SVG ovals onto the glyphs from \iint and \iiint.

_**Edit by @ylemkimon:** This pull request fixes #392._

### CODE REVIEW

**Comment by ronkok** [comment]
Here's screenshot:

oiint

**Comment by ronkok** [comment]
I submitted this PR too soon. It doesn't position `sub` elements correctly. I'll fix it.

**Comment by kevinbarabash** [comment]
Nice.  I was going to try to add glyphs to the fonts, but this is better b/c it should save space.

**Comment by ronkok** [comment]
There. I've got the `sub` fixed and tests are in. This is ready for review.

**Comment by ronkok** [comment]
> this is better b/c it should save space.

Yes, it will save some space. That comes at the cost of several exceptions cluttering up the code. I would be happy to see someone come along and replace this with font glyphs.

**Comment by kevinbarabash** [comment]
> Yes, it will save some space. That comes at the cost of several exceptions cluttering up the code. I would be happy to see someone come along and replace this with font glyphs.

I guess everything has it's drawbacks.  I agree that fewer exceptions is probably the right call here.

**Comment by kevinbarabash** [comment]
Here's the associated katex-fonts issues: https://github.com/KaTeX/katex-fonts/issues/20.  @ronkok I'm curious which package you got the geometry for the ellipses from.

**Comment by ronkok** [comment]
I liked the look of the MnSymbol ovals. Nicely curved, not too pinched at the end. So I started with its (public domain) path geometry. Of course, MnSymbol has different font glyphs than KaTeX, so I had to stretch the Size2 ovals and shrink the Size1 ovals. I think they came out pretty well.

**Comment by kevinbarabash** [comment]
@ronkok they look good!

**Comment by kevinbarabash** [comment]
@ylemkimon thanks for reviewing.

**Pull request merged**
