### PR TITLE
Fix \underset

### PR DESCRIPTION
**Pull request by ronkok**
This PR modifies `\underset` and `\overset` so that they will behave like LaTeX when an exponent is applied after the `\underset`. Fixes issue #1275.

I also changed the spacing from KaTeX `mop` to KaTeX `mrel`. The result seems to be a better match to LaTeX.

### CODE REVIEW

**Comment by ronkok** [comment]
Visual confirmation:
underset

**Comment by edemaine** [comment]
It looks like a few screenshots need to be updated.

**Comment by ronkok** [comment]
I have never mastered Docker and so am unable to update screenshotter tests. In the past, @kevinbarabash  has been kind enough to update them for the PRs that I submit. In the most recent example, he ran the test; then pasted the two relevant screenshot files into a comment on the PR's comment thread.  I took the png files and copied them into the screenshotter folder in that branch.

That could work again if anyone would care to help me out.

**Comment by edemaine** [comment]
I updated the screenshots for you (pushing directly to your branch).  Check out the https://github.com/Khan/KaTeX/pull/1277/files?short_path=da83f1e#diff-da83f1efcd086fe5f05c338688da3c18 to make sure it looks like the right new behavior.

**Comment by ronkok** [comment]
@edemaine  The new screenshots look perfect to me. Feel free to proceed with final approval and a merge.

**Pull request merged**
