### PR TITLE
Add version to katex object

### LINKED ISSUE #1190: katex.version
For debugging purposes, it would be handy if `katex.version` would return the version string for the loaded version of KaTeX.

### PR DESCRIPTION
**Pull request by EthanLuisMcDonough**
Fix #1190

### CODE REVIEW

**Comment by EthanLuisMcDonough** [comment]
Thanks for the feedback.  Changes have been made.

**Comment by edemaine** [comment]
@EthanLuisMcDonough Just checking: did you test that indeed `katex.version` returns the right version in a built version of `katex.js` / `katex.min.js` (e.g. using the test server run via `npm start`)?

**Comment by EthanLuisMcDonough** [comment]
Yes, I tested.  `katex.version` returns `"0.10.0-pre"`.

**Comment by edemaine** [comment]
I further confirmed that, after `npm build`, `build/katex.js` has a line starting
```js
module.exports = {"name":"katex","version":"0.10.0-pre",...
```
We'll want to make sure that this gets the actual build number when using the release script, but looks like it should work.

**Pull request merged**
