### PR TITLE
Add support for \kern

### PR DESCRIPTION
**Pull request by kevinbarabash**
Summary:
Addresses https://github.com/Khan/KaTeX/issues/422.
This only supports em and ex units and doesn't handle vertical layouts.
Negative kerning works.

Test Plan:
- make test
- make screenshots (verify that d is slightly overlapping c in the screenshots)

Reviewers: emily

### CODE REVIEW

**Comment by spicyj** [comment]
Can you add something with a changed font size to the screenshot, like a frac? Not sure offhand if the space should scale or not.

**Comment by kevinbarabash** [comment]
It looks like LaTeX is not scaling `\kern`.  Here are some screenshots.

LaTeX:
screen shot 2015-12-30 at 6 07 37 pm

KaTeX:
screen shot 2015-12-30 at 6 07 43 pm

**Comment by kevinbarabash** [comment]
It's a little hard to tell from the screenshot, but the distance between `a` and `b` in both the fraction and not-in-the-fraction is 87 pixels in both cases (as measured by dev tools inspector).
screen shot 2015-12-30 at 6 15 23 pm

**Comment by xymostech** [comment]
@kevinbarabash this looks good to me!

**Comment by kevinbarabash** [comment]
@xymostech thanks

**Pull request merged**
