### PR TITLE
added euro sign with \euro

### PR DESCRIPTION
**Pull request by henzestplus**
issue #254 is addressed here. Currently it' s just the \euro symbol as described in http://www.theiling.de/eurosym.html. I am willing to create a \EUR command, but since we don't really need it, I leave this for now. Maybe someone else can pick this up and continue my work.

### CODE REVIEW

**Comment by spicyj** [comment]
Why did the font files change/how did you generate them?

**Comment by henzestplus** [comment]
The euro sign was not embedded in any of the font files, since KaTeX uses them for display it only 'knows' what's in the font files. I used fontForge to,  basically,  copy the euro sign from another font (where this one was, presumably,  based on), and an online converter to get the other formats as well.

**Comment by spicyj** [comment]
The generation of the fonts is completely automated using these scripts:

https://github.com/Khan/KaTeX/tree/master/dockers/MathJaxFonts

We don't change them by hand. I am not sure if there is any euro symbol in the fonts (I find it hard to believe that there isn't) but we can't take this pull request in its current form.

**Comment by henzestplus** [comment]
There isn't any in the result files located in static/fonts. If generated through that, how can I ensure it will be in there? Do I have to add something to a script?

**Pull request closed without merging**
