### PR TITLE
Add section, paragraph and copyright as symbol

### PR DESCRIPTION
**Pull request by ysawa**
I have known some symbols in TeX do not exist in KaTeX. I have added

* Section mark
* Paragraph mark
* Copyright mark

to the symbols list. Would you be able to check them?

### CODE REVIEW

**Comment by ysawa** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
@ysawa thanks for the PR.  I don't think these symbols are actually in any of our fonts.  Do you know what TeX font (or package) they appear in?

**Comment by ysawa** [comment]
@kevinbarabash Those symbols may be LaTeX fonts 
 ( https://tex.stackexchange.com/questions/255127/why-is-the-copyright-symbol-in-helvet-asymmetric ) . Actually, they are not in KaTeX fonts, and I think it's better to use those text as normal HTML. Thank you.

**Comment by edemaine** [comment]
I've created https://github.com/KaTeX/katex-fonts/issues/9 to add these to the fonts.

**Pull request closed without merging**
