### PR TITLE
Mathjax Scraper

### PR DESCRIPTION
**Pull request by Kully**
For https://github.com/Khan/KaTeX/issues/905

I wrote a Python Scraper to grab all the functions from  http://docs.mathjax.org/en/latest/tex.html and inject them into the README. WDYT?

It's still a WIP.

To Do:
-  [ ] automate script excecution (i.e. `! python mathjax_scraper.py`)
-  [ ] inject the current KaTeX functions in the right column (https://github.com/Khan/KaTeX/issues/103) 

cc. @kevinbarabash @ronkok

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@Kully cool.  Injecting the KaTeX functions should be too hard b/c you can load functions.js, symbols.js, environments.js, and macros.js and then read the various tables which store those things.

**Comment by Kully** [comment]
> b/c you can load functions.js, symbols.js, environments.js, and macros.js and then read the various tables which store those things.

How would I do that?

Also, what do you think about a bash script that runs the script each time a commit is merged or something like that? So that we are automating the README updating

**Comment by ronkok** [comment]
This is an excellent idea. It can take the place of [this page](http://utensil-site.github.io/available-in-katex/), which seems to be un-maintained these days.

I wonder, though, if the README page is the best place. README already has a lot of information. Maybe a page in the [wiki](https://github.com/khan/katex/wiki) would be better?

**Comment by kevinbarabash** [comment]
> I wonder, though, if the README page is the best place. README already has a lot of information. Maybe a page in the wiki would be better?

I agree that it feels like too much info for the README.  I'm not sure how difficult it would be to update the wiki with a script.  I guess we could manually copy/paste it in there.  Maybe a `FEATURES.md` or something like that.

**Comment by Kully** [comment]
> This is an excellent idea. It can take the place of this page

Do either of you know why that page isn't rendering properly? It was from an old PR iirc

**Comment by ronkok** [comment]
That page took its KaTeX from the `bower` distribution. These days, `bower` is deprecated and KaTeX now uses `jsdelivr` for its CDN. So its link to KaTeX is a dead link. I've made a PR to that repository that would update the link. No response.

**Comment by kevinbarabash** [comment]
> > b/c you can load functions.js, symbols.js, environments.js, and macros.js and then read the various tables which store those things.

> How would I do that?

@Kully I was thinking something along the lines:
```
import symbols from "./src/symbols.js";
import functions from "./src/functions.js";
import environments from "./src/environments.js";
import macros from "./src/macros.js";

const commands = [
   ...Object.keys(symbols.math),
   ...Object.keys(symbols.text),
   ...Object.keys(functions),
   ...Object.keys(environments),
   ...Object.keys(macros),
].sort();

// inject commands in .md file
```

**Comment by kevinbarabash** [comment]
I think the difficult it how to make the JS code work with your python code.  I would probably rewrite the python code in JS and then you'd be able to easily access the KaTeX and MathJax list of commands at the same time.

**Comment by kevinbarabash** [comment]
@Kully will you be able to update this PR?

**Comment by Kully** [comment]
> @Kully will you be able to update this PR?

Yes I will, I am just on vacation for the month of July.

**Comment by ylemkimon** [comment]
Closing in favor of #1536. Thank you for your contribution!

**Pull request closed without merging**
