### PR TITLE
Export render math in text function

### PR DESCRIPTION
**Pull request by johnmcconnell**
Closes: https://github.com/Khan/KaTeX/issues/741

### CODE REVIEW

**Comment by johnmcconnell** [comment]
[clabot:check]

**Comment by johnmcconnell** [comment]
@xymostech Yeah, totally. They are not exported as `window.renderMathInText` and `window.renderMathInElement`.

It is `window.renderMathInElement.window.renderMathInText`. I'll make the changes.

**Comment by kevinbarabash** [comment]
@johnmcconnell will you have time to make the changes that xymostech requested?

**Comment by johnmcconnell** [comment]
Not anytime soon. Feel free to close the issue

**Comment by kevinbarabash** [comment]
@johnmcconnell feel free to re-open.

**Pull request closed without merging**
