### PR TITLE
Improve horizontal spacing of fractions

### PR DESCRIPTION
**Pull request by gagern**
A fraction is surrounded by a box of width `\nulldelimiterspace` on either side.
That size is 1.2pt and does not scale with the style or font size.
Furthermore, a `\frac` creates a brace-enclosed group which results in a `\mathord`, not a `\mathinner`.

This addresses #249. I'll attach visual diffs of the changed screenshots in a moment.

### CODE REVIEW

**Comment by gagern** [comment]
I'm displaying two diffs for each test case. The first is old file in red and new file in green, the second is new file in red and LaTeX in green.

## Arrays:
arrays-firefox
arrays

## BinomTest
binomtest-firefox
binomtest

## DeepFontSizing
deepfontsizing-firefox
There is no comparison against TeX for this one, since deep font sizing doesn't work there yet.

## DisplayMode
displaymode-firefox
displaymode

## DisplayStyle
displaystyle-firefox
displaystyle

## FractionTest
fractiontest-firefox
fractiontest
I've added some extra text to this one, to catch some of the group type related issues described in https://github.com/mathjax/MathJax/issues/969.

## NestedFractions
nestedfractions-firefox
nestedfractions

## Phantom
phantom-firefox
phantom

## RlapBug
rlapbug-firefox
rlapbug

## Text
text-firefox
text

On the whole I'd say the changes are all going in the right direction, even though some of the cases are not yet as close to the TeX rendering as one would wish.

By the way: the second image for each test case was created by the newly merged `texcmp` utility. The first was the result of the following command:

```sh
rm -rf imgdiff
mkdir imgdiff
for i in $(git status --porcelain test/screenshotter/images | awk '/^.M /{print $2}'); do
  git show HEAD:$i | convert \
  \( $i -grayscale Rec709Luminance \) \( png:- -grayscale Rec709Luminance \) \
  \( -clone 0-1 -compose darken -composite \) -channel RGB -combine -trim imgdiff/${i##*/}
done
```

**Comment by xymostech** [comment]
Looks good to me! :+1: @kevinb7 any thoughts?

**Comment by kevinb7** [comment]
@gagern sorry for not responding earlier.  I saw this one morning and thought "this is awesome" and then I got side-tracked.  @xymostech big improvement, especially with fractions.  LGTM ^_^.

**Comment by kevinb7** [comment]
I think we'll find lots of uses for ```makeNullDelimiter```.

**Comment by kevinb7** [comment]
Thanks for the pull request.

**Pull request merged**
