### PR TITLE
Added support for visual depiction of unsupported commands

### PR DESCRIPTION
**Pull request by JeffEverett**
Addresses issue #273.

This patch adds two new options to the parser: `breakOnUnsupportedCmds` and `errorColor`. By default, `breakOnUnsupportedCmds` is `true` and `errorColor` is `#cc0000`. 

When `breakOnUnsupportedCmds` is `true`, the parser and renderer remain unchanged by the patch and unsupported commands in the input expression continue to result in `ParseError`s. When `breakOnUnsupportedCmds` is manually set to `false`, however, the command string will render as textual output in the color given by `errorColor`. This is achieved by the parser generating an `error` node for each unsupported command with a `value` property equal to an array of `textord`s corresponding to the command string. Having the `value` property equal to an array of `textord`s is useful because it allows the renderer to piggyback on the existing rendering capabilities of `text` nodes, which behave similarly.

Jasmine test and screenshotter tests have been added for this patch. In order to successfully create the screenshotter test for this addition, support for changing the settings used in the screenshotter for the two new options have been added. `breakOnUnsupportedCmds` can be set to `false` by setting `doNotBreak` in the query string to a non-empty string and `errorColor` can be set by including it as a name-value pair in the query string.

### CODE REVIEW

**Comment by kevinb7** [comment]
@JeffEverett thanks adding this.  I think this will be a huge benefit for anyone using KaTeX, especially for interactive typesetting.  Love the screenshots.  There are a few changes that I'd like to see.  Could you wrap the error node in a color node in the Parser?  That way we won't have to add a "settings" param to everything in buildHTML and buildMathML.  Also, if the "error" node is wrapped in a color node it could just be a "text" node and then we won't need a special "error" group type handler in buildHTML and buildMathML.

**Comment by JeffEverett** [comment]
@kevinb7 Good suggestions. That should make this PR more compact. I'll get on this soon.

**Comment by JeffEverett** [comment]
@kevinb7 I implemented your suggestions. I think the patch is a lot cleaner now.

I also added the two new properties to the readme file.

**Comment by kevinb7** [comment]
Thanks for the pull request.  Can't wait to start using this.

**Comment by spicyj** [comment]
Can we not use abbreviations like "Cmds", especially in public API?

**Comment by kevinb7** [comment]
I think that's a good idea.

**Comment by JeffEverett** [comment]
@spicyj I'll avoid using abbreviations in future contributions. Would you like me to change the option name for this one as well?

**Comment by spicyj** [comment]
@JeffEverett Yes please! I don't love the name `breakOnUnsupportedCommands` because it is pretty long but I don't have any better ideas.

**Pull request merged**
