### PR TITLE
Automate screenshotter

### PR DESCRIPTION
**Pull request by kevinb7**
Replacing the original pull request which was against master with this one which is against the branch making it easier to merge.

### CODE REVIEW

**Comment by gagern** [comment]
There is a known problem with the `Lap` example, wich sometimes yields different answers. See https://github.com/Khan/KaTeX/pull/264#issuecomment-114272707. Would it make sense to exclude that example in this test run?

**Comment by kevinb7** [comment]
I'd like to compare both renderings against LaTeX's rendering before taking any action here.

**Comment by gagern** [comment]
I'm making good progress with automatically generating PNGs from LaTeX as well. I guess I'll describe a docker for that, too, to fix the texlive version we're using as well as the ghostscript driver which does the rasterization for imagemagick.

**Comment by kevinb7** [comment]
This is exciting.  I think this will help a lot with adding new features and finding bugs.  
+1 for imagemagick.

**Comment by kevinb7** [comment]
Closing because automating docker on travis-ci is better than having a separate implementation.

**Pull request closed without merging**
