### PR TITLE
Add MathML rendering to improve accessibility

### PR DESCRIPTION
**Pull request by xymostech**
Summary: This adds support for rendering KaTeX to both HTML and MathML
with the intent of improving accessibility. To accomplish this, both
MathML and HTML are rendered, but with the MathML visually hidden and
the HTML spans aria-hidden. Hopefully, this should produce much better
accessibility for KaTeX.

Should fix/improve #38

Test plan:
 - Ensure all the tests, and the new tests, still pass.
 - Ensure that for each of the group types in `buildHTML.js`, there is a
   corresponding one in `buildMathML.js`.
 - Ensure that the huxley screenshots didn't change (except for
   BinomTest, which changed because I fixed a bug in `buildHTML` where
   `genfrac` didn't have a `groupToType` mapping).
 - Run ChromeVox on the test page, render some math. (for example,
   `\sqrt{x^2}`)
   - Ensure that a mathy-sounding expression is read. (I hear "group
     square root of x squared math").
   - Ensure that nothing else is read (like no "x" or "2").
 - Ensure that MathML markup is generated correctly and is interpreted
   by the browser correctly by running
   `document.getElementById("math").innerHTML =
   katex.renderToString("\\sqrt{x^2}");` and seeing that the same speech
   is read.

### CODE REVIEW

**Comment by xymostech** [comment]
@spicyj @jeresig Here's the change, would love a review.

I set up a testing site at http://katex.xymostech.com/ If anyone with a screenreader would like to test it out, that would be great!

**Comment by fred-wang** [comment]
> I set up a testing site at http://katex.xymostech.com/ If anyone with a screenreader would like to test it out, that would be great!

The first minus sign is incorrectly converted into an mi element (instead of an mo element).

**Comment by xymostech** [comment]
Hmm, you are correct. That's probably because when we build the HTML tree, we change some of the parse tree in accordance with how TeX works. I'll switch the order of how we build things, but we should probably stop doing that some time in the future...

**Comment by fred-wang** [comment]
I just got a reply from Chris Fleizach (Apple, VoiceOver):
> I did some basic testing and it seems to be working as expected, so it’s looking good!

**Comment by xymostech** [comment]
> note the default value on a ∑ mo is largeop="true"

@fred-wang Interesting. Is there a place where that is documented? [This table](http://www.w3.org/TR/MathML/chapter3.html#presm.mo.dict.attrs) seems to indicate that the default is always `largeop="false"`.

I also found [this stackoverflow question](http://stackoverflow.com/questions/4697100/accessibility-recommended-alt-text-convention-for-svg-and-mathml) about adding alt text for math nodes. I'm a little hesitant about using the `<semantics>` tag because it doesn't look like it's supported anywhere but in Firefox. I guess MathML itself isn't that well supported either in other browsers (:disappointed:), but I'd worry about breaking support on things that work now. What do you think?

> > I did some basic testing and it seems to be working as expected, so it’s looking good!

Sounds great!

**Comment by fred-wang** [comment]
> Interesting. Is there a place where that is documented? This table seems to indicate that the default is always largeop="false".

The table has "set by dictionary (false)" so this means we pick the value from the dictionary or otherwise fallback to "false". The MathML3 dictionary is http://www.w3.org/TR/MathML/appendixc.html and is used in Gecko-based, WebKit-based browsers, MathJax etc

> I'm a little hesitant about using the <semantics> tag because it doesn't look like it's supported anywhere but in Firefox. I guess MathML itself isn't that well supported either in other browsers (:disappointed:), but I'd worry about breaking support on things that work now. What do you think?

I'm not sure what you mean by "not supported". Gecko-based and WebKit-based browsers have MathML support (including for the semantics tag). Even recent Blink-based browsers have some support for the semantics element: the TeX source is shown to workaround the lack of native MathML support. But semantics support should be irrelevant for accessibility? Or maybe Chrome's semantics implementation is breaking support in ChromeVox? (in that case they will probably fix that soon, since Wikipedia uses the semantics element too and I ask them to test it... and it's just a matter of overriding the default CSS stylesheet).

Also, I personally think people should use and encourage standards so "Chrome does not support MathML rendering" is never an excuse ;-)

> I also found this stackoverflow question about adding alt text for math nodes. 

As I recall, altext is more to provide a readable description equivalent to alt (the page you mention indicates "spoken math" not source) while semantics is to provide alternative representation of the formula (TeX source, image etc) that can be accessed by copy and paste etc I know that tools like LaTeXML use the TeX source for alttext and put it in a semantics annotation too... Wikipedia uses the semantics annotation. And I believe MathJax has an option to expose the TeX as a semantics annotation.

**Comment by xymostech** [comment]
Ah, I hadn't seen that table. Very interesting!

These are good points. I'll add in the semantics tag!

**Pull request closed without merging**
