### PR TITLE
Fix \boxed, add \overbracket

### PR DESCRIPTION
**Pull request by ronkok**
This PR introduces `buildCommon.makeImageVList`, an alternate to `makeVList`,
for use when one element is on the baseline and the other element is an
image. Unlike `makeVList`, the new function aligns the image correctly even if 
image height > 1 em.

The PR then uses `makeImageList` to fix `\boxed` and adds two new
functions: `\overbracket` and `\underbracket`.

This PR is also a stepping stone to work that could resolve issue #60.

### CODE REVIEW

**Comment by ronkok** [comment]
Since I have never mastered Screenshotter, I would appreciate any help. It all looks pretty good on my [test page](http://copyasmarkup.com/katex/wideelements.html).

**Comment by kevinbarabash** [comment]
> Since I have never mastered Screenshotter, I would appreciate any help. It all looks pretty good on my test page.

I can help out, but it would be good to diagnose the screenshotter issue as well as other people may run into the same issue.

**Comment by ronkok** [comment]
Oh, my issues run deeper than Screenshotter. I work in Windows. Now, I know that `make` files, `bash` scripts, and Docker are all possible within Windows. They take more effort to learn and the documentation is scattered, incomplete, and often outdated or misleading. But doable, given effort. Which I have not exerted.

Which means that my root problem is sloth.

**Comment by kevinbarabash** [comment]
I thought closing/reopening might fix the travis-ci issue.  I've sent github support an email about the issue.

**Comment by kevinbarabash** [comment]
There we go.

**Comment by kevinbarabash** [comment]
Hmm.. not sure why the `Boxed` screenshots are failing.  I'll look at it this evening.

**Comment by kevinbarabash** [comment]
I see what the issue is.  I didn't commit the changes to ss_data.yaml.  I can fix that.

**Comment by kevinbarabash** [comment]
When comparing the updated images for HorizontalBraces using the swipe feature I noticed that the underbrace is no longer centered when it should be.

horizontalbraces

Another difference from LaTeX that this test points out is that the effect of `\displaystyle` should continue past the group that immediately follows it.  Notice how large the fraction is.  I'll open a separate issue for this.

**Comment by ronkok** [comment]
Re: Centering. I must have introduced a CSS bug with this PR. I'll fix that, but it may be a few days before I get to it. Things are a little hectic right now.

**Comment by ronkok** [comment]
@kevinbarabash, I've reworked `makeImageVList`. It is now possible to center the text argument on a longer image argument. Naturally, the screenshotter images have issues.

I've also made a couple of edits in `buildHML.js` that were necessary to keep up with the rapid changes to other parts of KaTeX.  GitHub is declaring those to be conflicts, and I'm really not sure why.

**Comment by kevinbarabash** [comment]
@ronkok it's possible that github is treating https://github.com/Khan/KaTeX/pull/765, which was merged recently, as a conflict.

**Comment by ronkok** [comment]
Screenshotter error again.

**Comment by kevinbarabash** [comment]
I'm confused as to why the updated files aren't showing up in this PR. :|

**Comment by ronkok** [comment]
Well it you are confused, then I am bewildered. I would be willing to try again, if you want to try another PR.

**Comment by kevinbarabash** [comment]
Looks like it's `StrikeThrough` that I should've regenerate screenshots for.

**Comment by ronkok** [comment]
@kevinbarabash, It's probably not worth spending any more time on this PR. @kohler's PR#768 solves the same problem as `makeImageVList` and #768 does it in a more general way.

I'll leave this PR open for a bit longer, but I expect to close it in preference for #768.

**Comment by ronkok** [comment]
Closing this PR in favor of PR #768.

**Pull request closed without merging**
