### PR TITLE
Ignore `font' groups when determining base elements, fixes #390

### LINKED ISSUE #390: Subscripts wrong baseline
Rendering a subscript like `x_A, y_A` renders the subscript of the y lower then the subscirpt of the x. Probably because it uses the boundingbox of the letter it is subscripting.

Attached is a reference rendering from LaTeX
latex

And the output from KaTeX
xatex

### PR DESCRIPTION
**Pull request by mathijshenquet**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@mathijshenquet what problem is this solving?

**Comment by kevinbarabash** [comment]
@mathijshenquet thanks for fixing https://github.com/Khan/KaTeX/issues/390.  Could you add a screenshot test?  You'll need to add a test case to https://github.com/Khan/KaTeX/blob/master/test/screenshotter/ss_data.yaml and then run `make screenshots`.

**Comment by kevinbarabash** [comment]
@mathijshenquet sorry for not seeing the update.  Thanks for adding screenshots, they look great!  Before I can merge this though can you sign our contrinbutor license agreement?

www.khanacademy.org/r/cla

**Comment by kevinbarabash** [comment]
@mathijshenquet friendly ping about signing our CLA.

**Comment by mathijshenquet** [comment]
@kevinbarabash I signed the agreement. Sorry for not responding earlier (I was away on holiday).

**Pull request merged**
