### PR TITLE
Support Unicode arrows

### PR DESCRIPTION
**Pull request by ronkok**
This is the second in a series of PRs to give KaTeX the ability to recognize Unicode character input.

All the characters in this PR will produce `rel` atoms.

### CODE REVIEW

**Comment by ronkok** [comment]
As in PR #933, the following table shows the KaTeX function to which each character is mapped, and confirmation whether [unicode math](http://ctan.sharelatex.com/tex-archive/macros/latex/contrib/unicode-math/unicode-math-table.tex) and/or John Cook’s [conversion page](https://www.johndcook.com/unidata.js) map it the same way.

  

| **Character** | **Code point** | **Maps to**                       | **unicode math**     | **Cook**                                   | **Other**                                                        |
|:-------------:|:--------------:|:----------------------------------|:--------------------:|:------------------------------------------:|:-----------------------------------------------------------------|
| ←             | U+2190         | \\leftarrow                       | ✓                    | \\leftarrow \\shortleftarrow               | \\gets                                                           |
| ↑             | U+2191         | \\uparrow                         | ✓                    | \\uparrow \\shortuparrow                   |                                                                  |
| →             | U+2192         | \\rightarrow                      | ✓                    | \\rightarrow \\shortrightarrow             | \\to, \\vec, \\overrightarrow \\underrightarrow \\xrightarrow    |
| ↓             | U+2193         | \\downarrow                       | ✓                    | \\downarrow \\shortdownarrow               |                                                                  |
| ↔             | U+2194         | \\leftrightarrow                  | ✓                    | ✓                                          | \\overleftrightarrow \\underleftrightarrow \\underleftrightarrow |
| ↕             | U+2195         | \\updownarrow                     | ✓                    | ✓                                          |                                                                  |
| ↖             | U+2196         | \\nwarrow                         | ✓                    | ✓                                          |                                                                  |
| ↗             | U+2197         | \\nearrow                         | ✓                    | ✓                                          |                                                                  |
| ↘             | U+2198         | \\searrow                         | ✓                    | ✓                                          |                                                                  |
| ↙             | U+2199         | \\swarrow                         | ✓                    | ✓                                          |                                                                  |
| ↚             | U+219A         | \\nleftarrow                      | ✓                    | ✓                                          |                                                                  |
| ↛             | U+219B         | \\nrightarrow                     | ✓                    | ✓                                          |                                                                  |
| ↞             | U+219E         | \\twoheadleftarrow                | ✓                    | ✓                                          | \\xtwoheadleftarrow                                              |
| ↠             | U+21A0         | \\twoheadrightarrow               | ✓                    | ✓                                          | \\xtwoheadrightarrow                                             |
| ↢             | U+21A2         | \\leftarrowtail                   | ✓                    | ✓                                          |                                                                  |
| ↣             | U+21A3         | \\rightarrowtail                  | ✓                    | ✓                                          |                                                                  |
| ↦             | U+21A6         | \\mapsto                          | ✓                    | ✓                                          | \\xmapsto                                                        |
| ↩             | U+21A9         | \\hookleftarrow                   | ✓                    | ✓                                          | \\xhookleftarrow                                                 |
| ↪             | U+21AA         | \\hookrightarrow                  | ✓                    | ✓                                          | \\xhookrightarrow                                                |
| ↫             | U+21AB         | \\looparrowleft                   | ✓                    | ✓                                          |                                                                  |
| ↬             | U+21AC         | \\looparrowright                  | ✓                    | ✓                                          |                                                                  |
| ↭             | U+21AD         | \\leftrightsquigarrow             | ✓                    | \\leftrightsquigarrow \\leftrightwavyarrow |                                                                  |
| ↮             | U+21AE         | \\nleftrightarrow                 | ✓                    | ✓                                          |                                                                  |
| ↰             | U+21B0         | \\Lsh                             | ✓                    | ✓                                          |                                                                  |
| ↱             | U+21B1         | \\Rsh                             | ✓                    | ✓                                          |                                                                  |
| ↶             | U+21B6         | \\curvearrowleft                  | ✓                    | ✓                                          |                                                                  |
| ↷             | U+21B7         | \\curvearrowright                 | ✓                    | ✓                                          |                                                                  |
| **↺**         | U+21BA         | \\circlearrowleft<sup>(AMS)</sup> | \\acwopencirclearrow | \\acwopencirclearrow                       |                                                                  |
| **↻**         | U+21BB         | \\circlearrowright(AMS)           | \\cwopencirclearrow  | \\cwopencirclearrow                        |                                                                  |
| ↼             | U+21BC         | \\leftharpoonup                   | ✓                    | ✓                                          | \\overleftharpoon, \\xleftharpoonup                              |
| ↽             | U+21BD         | \\leftharpoondown                 | ✓                    | ✓                                          | \\xleftharpoondown                                               |
| ↾             | U+21BE         | \\upharpoonright                  | ✓                    | ✓                                          |                                                                  |
| ↾             | U+21BE         | \\upharpoonright                  | ✓                    | ✓                                          | \\restriction                                                    |
| ↿             | U+21BF         | \\upharpoonleft                   | ✓                    | ✓                                          |                                                                  |
| ⇀             | U+21C0         | \\rightharpoonup                  | ✓                    | ✓                                          | \\overrightharpoon \\xrightharpoonup                             |
| ⇁             | U+21C1         | \\rightharpoondown                | ✓                    | ✓                                          | \\xrightharpoondown                                              |
| ⇂             | U+21C2         | \\downharpoonright                | ✓                    | ✓                                          |                                                                  |
| ⇃             | U+21C3         | \\downharpoonleft                 | ✓                    | ✓                                          |                                                                  |
| ⇄             | U+21C4         | \\rightleftarrows                 | ✓                    | ✓                                          | \\xtofrom                                                        |
| ⇆             | U+21C6         | \\leftrightarrows                 | ✓                    | ✓                                          |                                                                  |
| ⇇             | U+21C7         | \\leftleftarrows                  | ✓                    | ✓                                          |                                                                  |
| ⇈             | U+21C8         | \\upuparrows                      | ✓                    | ✓                                          |                                                                  |
| ⇉             | U+21C9         | \\rightrightarrows                | ✓                    | ✓                                          |                                                                  |
| ⇊             | U+21CA         | \\downdownarrows                  | ✓                    | ✓                                          |                                                                  |
| ⇋             | U+21CB         | \\leftrightharpoons               | ✓                    | ✓                                          | \\xleftrightharpoons                                             |
| ⇌             | U+21CC         | \\rightleftharpoons               | ✓                    | ✓                                          | \\xrightleftharpoons                                             |
| ⇍             | U+21CD         | \\nLeftarrow                      | ✓                    | ✓                                          |                                                                  |
| ⇎             | U+21CE         | \\nLeftrightarrow                 | ✓                    | ✓                                          |                                                                  |
| ⇏             | U+21CF         | \\nRightarrow                     | ✓                    | ✓                                          |                                                                  |
| ⇐             | U+21D0         | \\Leftarrow                       | ✓                    | ✓                                          | \\xLeftarrow                                                     |
| ⇑             | U+21D1         | \\Uparrow                         | ✓                    | \\Uparrow \\Uparrowhead                    |                                                                  |
| ⇒             | U+21D2         | \\Rightarrow                      | ✓                    | ✓                                          | xRightarrow                                                      |
| ⇓             | U+21D3         | \\Downarrow                       | ✓                    | \\Downarrow \\Downarrowhead                |                                                                  |
| ⇔             | U+21D4         | \\Leftrightarrow                  | ✓                    | ✓                                          | \\xLeftrightarrow                                                |
| ⇕             | U+21D5         | \\Updownarrow                     | ✓                    | ✓                                          |                                                                  |
| ⇚             | U+21DA         | \\Lleftarrow                      | ✓                    | ✓                                          |                                                                  |
| ⇛             | U+21DB         | \\Rrightarrow                     | ✓                    | ✓                                          |                                                                  |
| ⇝             | U+21DD         | \\rightsquigarrow                 | ✓                    | \\rightzigzagarrow                         | \\leadsto                                                        |
| **⇠**         | U+21E0         | \\dashleftarrow(AMS)              | \\leftdasharrow      | \\leftdasharrow \\leftdasharrowhead        |                                                                  |
| **⇢**         | U+21E2         | \\dashrightarrow(AMS)             | \\rightdasharrow     | \\rightdasharrow \\rightdasharrowhead      |                                                                  |
| ⟵             | U+27F5         | \\longleftarrow                   | ✓                    | ✓                                          |                                                                  |
| ⟶             | U+27F6         | \\longrightarrow                  | ✓                    | ✓                                          |                                                                  |
| ⟷             | U+27F7         | \\longleftrightarrow              | ✓                    | ✓                                          |                                                                  |
| ⟸             | U+27F8         | \\Longleftarrow                   | ✓                    | ✓                                          | \\impliedby                                                      |
| ⟹             | U+27F9         | \\Longrightarrow                  | ✓                    | ✓                                          | \\implies                                                        |
| ⟺             | U+27FA         | \\Longleftrightarrow              | ✓                    | ✓                                          | \\iff                                                            |
| ⟼             | U+27FC         | \\longmapsto                      | ✓                    | ✓                                          |                                                                  |

**Comment by ronkok** [comment]
As you can see in the table above, this PR contains a few items where I disagree with the mapping chosen by `unicode math`.  They are all items that have perfectly good AMS functions. Despite that, `unicode math` chose to invent their own unnecessary synonyms.

By *synonym* I mean that the two functions:
1.  Have identical MathML results.
2. Have identical HTML results.
3. The sameness goes deeper than final output. They are also identical while in the DOM tree and while in the MathML tree.

For such synonyms, it doesn't matter which one we map to. 

In order to use the `unicode math` mapping, I would have to add code, such as:
````
defineSymbol(math, ams, rel, "\u21ba", "\\acwopencirclearrow", true);
````

That line of code would accomplish nothing. So I would rather not add it. On the other hand, it doesn't harm much either. KaTeX behavior would not change. It just adds one line of code bloat.

**Comment by ronkok** [comment]
I made a second commit, af5954d, to fix the lint error. That commit does not seem to be recognized here. Any suggestions would be welcome.

**Comment by ronkok** [comment]
I've updated the [test page](http://copyasmarkup.com/katex/Investigate.html)

**Comment by kevinbarabash** [comment]
Are the symbols with synonyms identical when rendered in LaTeX?

> That line of code would accomplish nothing. So I would rather not add it.

It does nothing because `\u21ba` would already map to `\circlearrowleft`?  It would define `\\ acwopencirclearrow`, but I doubt many people use that even if they're using `unicode-math`.

**Comment by ronkok** [comment]
> It does nothing because `\u21ba` would already map to `\circlearrowleft`?

Those are my thoughts exactly. I see no point for `\acwopencirclearrow`.

Now for a bit of wild speculation as to why they invented another function.  `unicode math` maps characters not just in the BMP, but also in the Unicode ranges for Bold Latin, Italic Latin, etc, etc. So they end up mapping 2400 characters to TeX-like functions. They had to invent a lot of those function names, such as  `\BbbC` instead of `\mathbb{C}`. So they used naming schema. 

Now the speculation: They grew to like their schema and they like things to be orderly. Notice that in most arrow functions, the "left" or  "right" come at the beginning of the name. But in `\dashleftarrow`, the "left" is not at the beginning. How sloppy! Not orderly! Must change!

Okay, that's probably wrong. I have no idea why they invented a new function name. I just see no point in it.

**Comment by ronkok** [comment]
@kevinbarabash  One last thought. Obviously, I would prefer to not add that extra line of code. But my preference is lightly held. It's your call. If you want it in, let me know.

**Comment by edemaine** [comment]
Another alternative would be to define the aliases using the macros. The slight practical benefit is that then a user could override that make with custom macros. But I don't see that actually being that useful.

I'm fine with having the unicode symbol expand to what LaTeX would expand to, without defining the intermediate alias. Should probably document in a comment though.

**Comment by ronkok** [comment]
I am closing this PR so that I can resubmit it from a branch instead of from `master`.

**Pull request closed without merging**
