### PR TITLE
Resolved Issue #370

### PR DESCRIPTION
**Pull request by Newman101**
Resolved issue #370 in CONTRIBUTING.md by amending the broken link. 

Thank you.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@Newman101 thanks for the pull request.  The link label should be updated.  Also, before we can accept a pull request from you please sign our CLA: http://www.khanacademy.org/r/cla.

**Comment by Newman101** [comment]
CLA signed. I will update the link label ASAP.

**Comment by Newman101** [comment]
Link label updated. :)

**Comment by kevinbarabash** [comment]
@Newman101 thanks!

**Pull request merged**
