### PR TITLE
Add support for \textsc.

### PR DESCRIPTION
**Pull request by msridhar**
This is a first attempt, and may still have issues.  In particular,
I am not sure what needs to be done for MathML rendering.

Fixes Khan/KaTeX#471

### CODE REVIEW

**Comment by msridhar** [comment]
Happy to address comments.  I Googled around for MathML and small caps, but couldn't find anything helpful.  So, I just used the same `fontMap` entry as `"mathrm"` in `buildCommon.js`.

**Comment by msridhar** [comment]
Just a ping for any feedback on this.  Happy to make changes.

**Comment by kevinbarabash** [comment]
@msridhar sorry for the delay.  Can you post some screenshots?  I'm not sure how the browser actually implements this.  If it's swapping out glyphs, e.g. using unicode small caps A (U+1D00) for every `a` then the browser will end up using a different font.  It might be scaling existing glyphs in the font if the font doesn't include specific small caps glyphs.  Either way, we don't have the metrics for those.  That being said, we only need the height and depth.  It looks like we could probably use the x-height of the font as the height for the small caps and since the small caps don't have descenders, the depth should be 0.

**Comment by msridhar** [comment]
screen shot 2016-05-27 at 10 20 25 am
Is this the kind of screenshot you're looking for?  Let me know if I should try some other text.

One thing you can see is that space characters seem to be getting ignored.  Typically they won't be needed, but I can try to look into why this is happening.

**Comment by kevinbarabash** [comment]
@msridhar could you have a look at why we're dropping spaces?  I want to check this branch out and play around with before merging it.  I'm concerned about how it handles vertical layouts especially since the font metrics are going to be wrong for the characters now.

**Comment by kevinbarabash** [comment]
This might be something we put behind a flag.

**Comment by kevinbarabash** [comment]
As for MathML support, you could try the `<mi mathvariant='small-caps'>ab</mi>` and see that works in your favorite MathML viewer.

**Comment by msridhar** [comment]
Thanks for the feedback! I'm on vacation now, will look in a couple weeks.

**Comment by edemaine** [comment]
@msridhar Any updates on this?

**Comment by msridhar** [comment]
@edemaine unfortunately I never had the time to pick up this work, and I likely won't have time soon.  The changes I made were quite simple, but I'm not sure what exactly it would take to address the remaining comments.

**Comment by kevinbarabash** [comment]
@msridhar sorry for the delay in responding.  There are two issues that still need to be resolved:
- getting the correct vertical metrics for each of the glyphs (lowercase y should not have any depth/descent, but its height/ascent should be greater than the standard y)... using the metrics from the standard 'y' when rendering a small caps 'y' will result in incorrect positioning in vertical layouts such as `\frac` and `\sqrt`.
- spaces should render as spaces

Here's what the `\textsc{Lorem Ipsum Dolar}` should look like according to quicklatex.com:
screen shot 2017-09-13 at 9 50 39 pm

**Comment by kevinbarabash** [comment]
I believe that the browser is doing something to the font to generate the small caps.  I found a tool called [cap-height](https://github.com/sebdesign/cap-height) that can measure the height of small caps so we could use it to figure out what the height should be.

**Comment by msridhar** [comment]
Hey, so if someone else could take this one over the finish line that'd be
great. I'm not going to have time in the near future.

**Comment by kevinbarabash** [comment]
@msridhar I'm going to close the PR for now.  I'll paste the details of what work remains in the issue if someone else wants to pick this up.

**Pull request closed without merging**
