### PR TITLE
Remove tree cloning before building HTML

### PR DESCRIPTION
**Pull request by ylemkimon**
Related #225.

The only place where tree is mutated was `accent`.

This also removes `JSON.stringify()` polyfill, which is about 2KB. (#1469)

### CODE REVIEW

**Comment by ylemkimon** [comment]
@edemaine I scanned through `htmlBuilder`s to find where `ParseNode`(group) was mutated. There was one place where `ParseNode` was temporarily modified, `functions/op.js` added by #1430. Other than that, it seemed `ParseNode`(group) is not touched.

Also, I've added helper code to throw an error if tree was modified during `buildHTML` and run `jest` test suites.

**Comment by edemaine** [comment]
Awesome.  Is it possible / a good idea to add that helper to the Jest test suite?  Or too messy / high overhead?

**Comment by ylemkimon** [comment]
@edemaine As it needs to access intermediate tree before building HTML, I've edited the `buildTree` function directly. I'm not sure of a good way to add this to the test helpers.

**Comment by edemaine** [comment]
@ylemkimon Hmm. If we're calling `parseTree` and `buildTree` separately in the tester, couldn't we duplicate the tree in between and then see if it changed during `buildTree`? Of course, #1336 should really be merged before tweaking any of this.

**Comment by ylemkimon** [comment]
@edemaine Unfortunately, we're calling them together in the test helpers by calling `katex.__renderToDomTree`.

**Comment by edemaine** [comment]
I guess an option would be to have an optional callback on `renderToDomTree` of what to do with the parse tree... but that may not be worth it.  I'm happy enough that you tested it for existing code.

**Comment by ylemkimon** [comment]
@edemaine It'd be nice to have some kinds of hooks system 😄

**Comment by kevinbarabash** [comment]
Something else we might look into to ensure that structures aren't mutated by accident is to use flow to mark objects as read-only.  See https://flow.org/en/docs/types/utilities/#toc-readonly for details.

**Pull request merged**
