### PR TITLE
Add smart quote example, as discussed in #967

### PR DESCRIPTION
**Pull request by edemaine**
This small PR adds a sentence of documentation out of the resolution of #967 (Render smart quotes in math as regular quotes).

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@edemaine I was thinking we'd have actually "gotchas" section, maybe called `# Common Issues` where we could list this as well as things like there not being enough space between rows in `{aligned}` when using fractions or the font being bigger than MathJax.  That way it would have better visibility.

**Comment by edemaine** [comment]
@kevinbarabash Sounds good! Feel free to start a new PR to replace this one, or appropriate this PR.

**Comment by kevinbarabash** [comment]
@edemaine will do sometime this weekend.

**Comment by kevinbarabash** [comment]
Closing in favor of #1034.

**Pull request closed without merging**
