### PR TITLE
Update Khan Academy logo

### PR DESCRIPTION
**Pull request by ylemkimon**

### CODE REVIEW

**Comment by ylemkimon** [comment]
@edemaine Last three elements are parts of the logo.

**Comment by kevinbarabash** [comment]
The contrast is pretty low between the green background and the teal of the logo.  Let me talk to our design team and see what they suggest.
screen shot 2018-08-16 at 9 53 20 pm

**Comment by ylemkimon** [comment]
@kevinbarabash Done 😄

**Comment by kevinbarabash** [comment]
@ylemkimon thank you.  That looks really nice.

**Pull request merged**
