### PR TITLE
Upgrade Yarn before installing dependencies, if needed

### PR DESCRIPTION
**Pull request by ylemkimon**
Fixes issue #1648.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
Did `yarn` change what running `yarn check` does?

**Comment by kevinbarabash** [comment]
What version of `yarn` should people being using for dev?

**Comment by ylemkimon** [comment]
@kevinbarabash Yarn speeds up the install process by skipping file copy if their size and modified time is equal. However, npm publish script removed and locked timestamps down to specific date: https://github.com/npm/npm/commit/114d518c75732c42acbef3acab36ba1d0fd724e2 and https://github.com/npm/npm/commit/58d2aa58d5f9c4db49f57a5f33952b3106778669. It's causing problems with old Yarn caching.

**Comment by ylemkimon** [comment]
Please hold off merging this for a while.

**Pull request closed without merging**
