### PR TITLE
Sync local doc with main doc for ignoredClasses

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by ylemkimon** [comment]
I was thinking of linking to the website, like main `README.md`.

**Comment by edemaine** [comment]
@ylemkimon Should we merge this for now, and do as a separate PR, or replace this with that PR?

**Comment by edemaine** [comment]
Closing in favor of #1566. Thanks @otacke for spotting the discrepancy!

**Comment by otacke** [comment]
@edemaine I kind of caused the discrepancy by my other contribution, so you're welcome ;-)

**Pull request closed without merging**
