### PR TITLE
Vertically center single-character \mathop.

### PR DESCRIPTION
**Pull request by kohler**
Fixes issue #726.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@kohler how did you test this?  Could you post some (before/after) screenshots `\mathop` expressions that are affected by this change?

**Comment by kohler** [comment]
Sure, I tested many expressions. Here's an expression that encompasses a lot of em

```
a\mathop+b\mathop:c\mathop{\delta}e\mathop{\textrm{and}}f\mathrel{\mathop{:}}=g\sin h
```

Before

image

After

image

Note that the `:`s moved up (as they should), the `\delta` moved down (as it should: https://tex.stackexchange.com/questions/368673/documentation-of-mathop), and the other ones stayed put (as they should).

**Comment by kohler** [comment]
NB Other uses of `groupTypes.op` that could have been affected, such as `\stackrel`, are tested in the screenshotter tests.

**Comment by kevinbarabash** [comment]
Looks good.  Can you add a screenshot test for that?  Screenshots for single tests can be generated using the `include` option, e.g. `dockers/Screenshotter/screenshotter.sh --include=Sqrt`.

**Comment by kohler** [comment]
test added

**Comment by edemaine** [comment]
Looks great!  Thanks for fixing this.

**Pull request merged**
