### PR TITLE
changelog for KaTeX - complete w/ links

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@Kully thanks for the PR.

**Comment by Kully** [comment]
> @Kully thanks for the PR.

You're welcome! My pleasure. 🎉

**Comment by edemaine** [comment]
Policy question: do we want to update CHANGELOG (for "master" version, say) as we add features going forward, PR by PR?  (Perhaps we should open a new discussion thread.)

**Comment by kevinbarabash** [comment]
Let's discuss in a new thread.

**Pull request merged**
