### PR TITLE
Keep unminified katex.js and katex.css build files

### LINKED ISSUE #547: Release unminified js and css
Currently working on integrating KaTeX into gitlab. Here it is a no-go to include minified sources. 

Would it be possible to also distribute the non-minified versions?

Gitlab MR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4638

### PR DESCRIPTION
**Pull request by deckar01**
Keep the unminified JavaScript and CSS files in the final build.

Fixes #547

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@deckar01 the changes seem reasonable to me.  @xymostech any thoughts on the matter?

**Comment by kevinbarabash** [comment]
Before we can accept this pull request we need you to sign our [Contributor License Agreement](https://khanacademy.org/r/cla).

**Comment by xymostech** [comment]
Looks good to me!

**Comment by xymostech** [comment]
[clabot:check]

**Comment by deckar01** [comment]
Thanks for reviewing @kevinbarabash and @xymostech.

**Pull request merged**
