### PR TITLE
Enable `greenkeeper-lockfile`

### PR DESCRIPTION
**Pull request by ylemkimon**
This can be enabled by one of following ways(CircleCI provides easier way to add SSH keys):

* GitHub repository deploy key([CircleCI docs](https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys))
  * [Generate a SSH key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key) without a passphrase
  * Add it to [repository deploy key settings](https://github.com/Khan/KaTeX/settings/keys) ([GitHub docs](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys))
  * Add it to [CircleCI SSH keys](https://circleci.com/gh/Khan/KaTeX/edit#ssh)
  * Add to CircleCI config or let me know the fingerprint
* GitHub user token
  * Create a account
  * Grant it a push access to `Khan/KaTeX`
  * Create a [GitHub access token](https://github.com/settings/tokens) with `public_repo` permission
  * Add it to [CircleCI environment variable settings](https://circleci.com/gh/Khan/KaTeX/edit#env-vars) ([CircleCI docs](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project)) as `GH_TOKEN`

CC @kevinbarabash

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@ylemkimon are you able to generate a repository deploy key or is this something I have to do?

**Comment by ylemkimon** [comment]
@kevinbarabash I can generate a SSH key, but only repo admin can add deploy key(public key) to the GitHub repository.

**Comment by ylemkimon** [comment]
Using user token is less secure, but allow access to GitHub APIs, e.g., #1166.

**Comment by kevinbarabash** [comment]
@ylemkimon okay, I've added SSH keys in the appropriate places.  How can we check that this actually works?

**Comment by ylemkimon** [comment]
@kevinbarabash The `hostname` is `github.com`, but as we don't use SSH for other things, I think we can leave it empty.

**Comment by ylemkimon** [comment]
@kevinbarabash I've added the SSH key and a step to check it working.

**Comment by ylemkimon** [comment]
@kevinbarabash I've confirmed it successfully gets added and authenticats: https://circleci.com/gh/Khan/KaTeX/3047. But it gives exit code 1 as it does not provide shell access, so I removed the test in #1479.

**Comment by ylemkimon** [comment]
@kevinbarabash Setting the host empty sets the `ssh_config` as:
```
Host !github.com *
  IdentitiesOnly no
```
which excludes `github.com` and makes read-only key take precedence.

Could you set the host to `github.com`?

**Pull request merged**
