### PR TITLE
Text commands dont stack right

### PR DESCRIPTION
**Pull request by rrandallcainc**
This is in an attempt to resolve: https://github.com/Khan/KaTeX/issues/676

This should theoretically allow for the stacking of font commands, if the font is available. Note: It currently does not work for `\textbf{\textit{x}}` because there is no "Main-BoldItalic" metrics available.

However, I've included the SansSerif-Bold/SansSerif-Italic to illustrate that `\textsf{\textbf{x}}` and `\textsf{\textit{x}}` will render a SansSerif bold/italic text respectively.

screen shot 2017-10-17 at 1 28 24 pm

screen shot 2017-10-17 at 1 28 30 pm

### CODE REVIEW

**Comment by rrandallcainc** [comment]
Closing until tests are fixed, and cleaned up.

**Comment by rrandallcainc** [comment]
@kevinbarabash I ran the screenshots locally, and while they are technically failing, I think the new screenshots are correct. 

That being said, would you mind taking a look? I am not very fluent in Latex, and I'd like someone with more experience to be able to verify.

**Comment by kevinbarabash** [comment]
@rrandallcainc the screenshots could probably be collapsed into a single screenshot using `{aligned}`.  I was thinking of doing this for the font screenshots for MathBf, MathCal, MathFrak, etc.  I'll review the code this weekend.

**Comment by rrandallcainc** [comment]
@kevinbarabash Good idea! I'm going to clean this up. I don't like how I approached some of this logic, and I think it could be improved. That being said, I expect it will be ready for this weekend. I'll remove the "needs-revision" label once it's ready.

**Comment by kevinbarabash** [comment]
@rrandallcainc are you still planning to clean up some of the logic?

**Comment by rrandallcainc** [comment]
@kevinbarabash Yes. I have been crazy busy lately. I'll be returning from a trip later this week. I would like to dedicate more time once I return. Thanks for your patience.

**Pull request closed without merging**
