### PR TITLE
Restructure functions, environments, symbols

### PR DESCRIPTION
**Pull request by gagern**
This addresses #255 and #256, currently one commit for each. Since both of these modify a pretty large portion of the code, and will likely conflict with many other things which are currently work in progress, I believe that it makes sense to keep these two commits together, so that people will only have to manually resolve conflicts on a larger scale once. The command

    git merge -s recursive -X ignore-all-space origin/master

or similar can be used to avoid conflicts which are solely due to changes in indentation. The resulting code might require reindentation, though. By the way, on my system these changes reduced the minified code size from 147496 to 135148 bytes. Mostly due to `symbols`, I guess. Makes me wonder whether `fontMetrics` should be switched to something which doesn't need names in the literals.

### CODE REVIEW

**Comment by kevinb7** [comment]
Even though I think this is moving in the right direction, I was hoping to have more discussion in https://github.com/Khan/KaTeX/issues/255 and https://github.com/Khan/KaTeX/issues/256 before getting a PR.  Sorry for not explicitly stating that.

> Since both of these modify a pretty large portion of the code, and will likely conflict with many other things which are currently work in progress, I believe that it makes sense to keep these two commits together, so that people will only have to manually resolve conflicts on a larger scale once.

I was hoping to merge https://github.com/Khan/KaTeX/pull/132 before doing any refactoring to avoid exactly this problem.  In the future please let us know before hand if you are planning to submit a large PR that might conflict with other peoples' work so that we can coordinate better moving forward.  

Thank you for suggesting ```git merge -s recursive -X ignore-all-space origin/master```.  Hopefully it will make resolving merge conflicts easier.

As for the changes themselves, I have a couple of comments:

There should probably be some convenience functions that set up the context objects and call the handlers.  If we had a ```Function``` class, each of the function objects it could have an ```invoke()``` method which the convenience methods would call.  Since we can't have a class called ```Function``` we could use ```Command``` which I think makes sense seeing that's what they're called in TeX.  Here's a sketch of what that might look like (some details have been omitted for the sake of brevity):
```
function Command(name, props, handler) {
    this.name = name;
    // extract props and handle defaults
    this.handler = handler;
}

Command.prototype.invoke = function(context, args, positions) {
   context.func = this.name;  // should probably probably rename func => name (or cmdName)
   this.handler.apply(context, args, positions);
};

function defineCommand(names, props, handler) {
   for (var i = 0; i < names.length; ++i) {
      module.exports[names[i]] = new Command(name, props, handler);
   }

Parser.prototype.invokeCommand = function(cmd, args, positions) {
   var context = {
       lexer: this.lexer,
       parser: this
   }
   cmd.invoke(context, args, positions);
};
```
If we combine ```ParseNode``` and ```ParseResult``` then the ```positions``` parameter would disappear.

I saw that you re-ordered some of the methods in buildHTML.js and buildMathML.js.  It would make it easier to review if the order was maintained when changing how they're defined.

I prefer ```define``` to ```declare``` because it seems to fit more with TeX vocab, i.e. ```\def```.  Also ```sym``` should be ```defineSymbol``` so that it follows the pattern.  It's longer but it should still be uglified to a single char.

It's nice to see a decrease in our minified code size.  With regards to shrinking fontMetrics, if we convert each entry to an array we should see an appreciable decrease in size as well.
```
{"8672":[-0.064,0.437,0,0]}
```
instead of 
```
{"8672":{"depth":-0.064,"height":0.437,"italic":0,"skew":0}
```

**Comment by gagern** [comment]
> Even though I think this is moving in the right direction, I was hoping to have more discussion in #255 and #256 before getting a PR. Sorry for not explicitly stating that.

I had assumed as much. But I didn't see a lot of discussion happening so far, so I wanted to make things more tangible. I expect that I'll probably be redoing the changes I did here one more time, after you've decided it's ready for merging. The equivalent of a rebase. But now you have something explict to discuss.

> was hoping to merge #132 before doing any refactoring

By all means, don't block other merges due to this. #132 in particular I'm very interested in. I need that more than I need this internal restructuring here.

I'm not sure I agree with the `Command` class you suggest. On the one hand, the step `context.func = this.name` means that you need a new `Command` instance for every command even if they share implementation, which currently isn't required with my approach. But, more severely, having the handler become part of a `Command` class and *still* have its `this` method not refer to that object, that feels even more weird than the `this` for current handlers. So I fear we might be adding confusion by making the handler look like a method when it is not.

On the other hand, I wholeheartedly agree with `Parser.prototype.invokeCommand` to avoid code duplication there. I also agree with your other suggestions. Regarding `sym` I'm indifferent. My main concern, why I chose such a short name, was that a longer name might cause problems with the 80 columns limit. I guess we're still a good distance away from that, though.

**Comment by kevinb7** [comment]
> But now you have something explict to discuss.

I always find talking about code easier.

> But, more severely, having the handler become part of a Command class and still have its this method not refer to that object, that feels even more weird than the this for current handlers.

Point taken.  The problem I was attempting to solve with this suggestion was getting rid of the need to pass information that the objects in funcs already have, e.g. name.  Here's how that might be accomplished without introducing a class.

```
function defineCommand(names, props, handler) {
   var data = { ... };
   for (var i = 0; i < names.length; ++i) {
      data.name = names[i];
      module.exports[names[i]] = data;
   }
}
```
```
Parser.prototype.invokeCommand = function(cmd, args, positions) {
   var context = {
       lexer: this.lexer,
       parser: this,
       name: cmd.name
   }
   cmd.handler.apply(context, args, positions);
};
```

**Comment by gagern** [comment]
@kevinb7 No, absolutely not! `data` is a *single* object, which gets passed around *by reference*. So each iteration of the loop would overwrite the name setting from the previous iteration, and in the end you have just the last name stick. My point is that currently, and with my setup, the function does *not* know its name, and it's cheaper that way since the parser knows that name just fine.

**Comment by kevinb7** [comment]
@gagern whoops... and fixing it would be kind of gross.

**Comment by kevinb7** [comment]
@gagern sounds good.  Can you make the change suggested in https://github.com/Khan/KaTeX/issues/255#issuecomment-114224682?

**Comment by gagern** [comment]
> Thank you for suggesting `git merge -s recursive -X ignore-all-space origin/master`. Hopefully it will make resolving merge conflicts easier.

It did so in a similar situation for me in the past. While we are at it, `git diff -b` (or even `git show -b`) will make reviewing this easier. (And the fact that we are not talking Python or CoffeeScript or some other language with semantic whitespace is really saving a lot of hassle here right now.)

**Comment by gagern** [comment]
> I was hoping to merge #132 before doing any refactoring

Any other in-flight pull requests you'd like to see merged before this one?

* The idea from #261 would benefit from the changes here, I think, but the actual implementation would need to be completely rewritten, so I see no urgent need to pull #261 in first. Even though that view might be slightly frustrating to the author.
* #174 you postponed past #250 which in turn I'd postpone past #266 which would be better off building on this here. The same probably holds for #149.
* #146 is probably already in conflict with #246 so it will require rebasing any way, might as well get rebased to take this one here into account as well.
* #140 sounds about ready for inclusion, so if I have to rebase this on #132, I might as well take that along. But #140 itself needs to rebased to use screenshotter instead of huxley. And it hasn't seen any review afaics.
* I don't know how close #135 is to completion. Should we wait on that, too?

Of course, as long as you agree with the general direction of the code changes here, I can build my next improvements on this, and then rebase them onto the version that eventually makes it into master.

**Comment by kevinb7** [comment]
Thanks for listing these out:
- I don't think we've reached consensus on what needs to be done with https://github.com/Khan/KaTeX/pull/261.  There's also not a lot of code there so rebasing shouldn't be too hard.
- I've closed https://github.com/Khan/KaTeX/pull/146.  They were minor refactorings and not critical.
- https://github.com/Khan/KaTeX/pull/140 can be done better with macros.  Adding a special ```not``` group handler to ```buildTree.js``` is not ideal.  I'm closing it as well.
- I think there's only a minor change I have to make with https://github.com/Khan/KaTeX/pull/135, but we can let this one sit.  If the codebase shifts underneath it not a big deal b/c there's not much code to rebase.
- I've already asked @xymostech to prioritize review of https://github.com/Khan/KaTeX/pull/132.  The plan is to finish the checklist this weekend and have her look at it next week.

> Of course, as long as you agree with the general direction of the code changes here, I can build my next improvements on this, and then rebase them onto the version that eventually makes it into master.

I would strongly urge against this approach.  If there's a refactoring that's necessary for a particular feature then that refactoring should be part of the pull request for that feature.  Large refactorings which make the code generally easier to understand or easier to work with should be done independently and if possible should be split into smaller logical pull requests so that they're easier to review.

**Comment by gagern** [comment]
> if possible should be split into smaller logical pull requests so that they're easier to review.

In that spirit, I suggest you review the two commits here separately, since each is a distinct change for different issue. As I wrote in https://github.com/Khan/KaTeX/issues/266#issuecomment-115748090 I'm willing to post them separately when the time for doing so is right, i.e. after #132.

**Comment by kevinb7** [comment]
@gagern sounds good.  I've responding in more detail in https://github.com/Khan/KaTeX/issues/266#issuecomment-115933756.

**Comment by gagern** [comment]
When I one day repost this here as 5 distinct pull requests, would you want me to write each as two distinct commits, one doing the actual modifications and one with just the reindentation? If you can do a `git diff -w` locally, there is nothing to be gained by separating stuff, but if you review here in GitHub, then having the whitespace changes out of the way might make things easier to review. At the cost of a longer history, of course.

**Comment by gagern** [comment]
Superseded by #345, #346, #347, #348, #356.

**Pull request closed without merging**
