### PR TITLE
Add latin-1 letters as math symbols

### PR DESCRIPTION
**Pull request by chrismessiah**
Currently katex throws an EOF parse error when receiving an input of latin-1 letters that is not inside a `\text{}` clause. To prevent this the latin-1 letters are added as math-symbols as well. 

skarmavbild 2017-08-16 kl 09 47 12

### CODE REVIEW

**Comment by spicyj** [comment]
I can't tell, is that Computer Modern in your screenshot? Not sure if our fonts support these chars.

**Comment by chrismessiah** [comment]
Good catch. Didn't notice that they were using different fonts. What is the procedure for adding such letters to the font? 

skarmavbild 2017-08-16 kl 21 46 54

**Comment by kevinbarabash** [comment]
Oh noes... we aren't using CM for latin-1 chars inside `\text` either.  Having this work correctly will require #632 and the some additional work to actually render combining marks for each of the accent types.  We'll also need to update how we calculate the height (ascent) and depth (descent) for the combined glyphs that we construct.  There's a fair amount of work involved so it's probably best to split it up.  I'm okay with this diff as is, but we should aim for rendering CM glyphs for latin-1 eventually.

**Comment by edemaine** [comment]
Given that KaTeX already supports math-mode accents, we should be able to macro each Latin-1 Unicode character in math mode to the corresponding accent command (ideally with a loop over the characters and a call to some Unicode splitting).

To fix Latin-1 characters in text mode, we should first do #638 (text-mode accent functions).  Then we can follow the above approach.

**Comment by kevinbarabash** [comment]
@edemaine can a macro be defined for something without a leading `\`?

**Comment by kevinbarabash** [comment]
I've added a project to track work relating to latin-1 support.

**Comment by edemaine** [comment]
@kevinbarabash No, macros currently need to start with `\`. But we could easily add support for single-character macros (in the spirit of TeX active characters). I'll give it a try...

**Comment by edemaine** [comment]
Moving discussion to #801

**Pull request merged**
