### PR TITLE
Add display mode to the CLI

### PR DESCRIPTION
**Pull request by mjbshaw**
This is a rehash of #242 (sorry I had to close that one; I forgot to go through Google's patching channels when I submitted it).

### CODE REVIEW

**Comment by kevinb7** [comment]
Cool.  I'm glad to see this back.  I was a little worried when I saw you close the other pull request this morning.

**Comment by kevinb7** [comment]
Have you signed a CLA yet?  
If not, please see https://github.com/Khan/KaTeX/blob/master/CONTRIBUTING.md#cla.

**Comment by mjbshaw** [comment]
Crap, I missed the part about the CLA. I haven't signed it. I'll check with Google's legal/open source department and get back to you on this one...

**Comment by spicyj** [comment]
Google's already signed the corporate CLA (via Max Sills) – not sure how we're supposed to verify that that covers you though. :)

**Comment by mjbshaw** [comment]
> Google's already signed the corporate CLA (via Max Sills) – not sure how
we're supposed to verify that that covers you though. :)

Yes, you seem to be right. It just wasn't listed in the list of
corporate-signed CLAs.

Okay, in that case it looks like we're all good, I believe. I'm not sure
how verification works if you need it, but I did commit using my @google.com
email so it should be associated with that rather than my personal email
address. I can --signoff the commit with a reference to the CLA if needed.

**Comment by spicyj** [comment]
I suppose the `@google.com` author should be good enough. I'll let @kevinb7 or @xymostech merge this one.

**Comment by xymostech** [comment]
Thanks!

**Pull request merged**
