### PR TITLE
Add \underline support

### LINKED ISSUE #209: \overline is present but not \underline
I may be missing something here, but isn't `\underline` part of LaTeX by default? Or was this omitted strategically?

### PR DESCRIPTION
**Pull request by spicyj**
image

Fixes #209.

### CODE REVIEW

**Comment by spicyj** [comment]
Having trouble getting Docker to work but it looks okay in my browser…

**Comment by kevinbarabash** [comment]
@spicyj cool.  Can you update the screenshot test to include `\overline` nested within `\underline` and vice versa?  I'll try running docker on your branch.

**Comment by spicyj** [comment]
Sure, I put it in the \blue{} to also prove that \underline preserves color.

**Comment by xymostech** [comment]
LGTM, once the tests pass!

**Comment by kevinbarabash** [comment]
yay!

**Pull request merged**
