### PR TITLE
Add configurable error callback

### PR DESCRIPTION
**Pull request by j-lenoch**
Replace console.error with a configurable option. This mimcs the current
default behaviour to guaranteee compatibility with previous versions.
Add errorCallback to the README.md

### CODE REVIEW

**Comment by j-lenoch** [comment]
[clabot:check]

**Comment by j-lenoch** [comment]
[clabot:check]

**Comment by edemaine** [comment]
This looks like a nice feature to add, but we should first merge #656 which provides a general framework for defining options; then we can add an `errorCallback` to the options object.

**Comment by edemaine** [comment]
@j-lenoch #656 finally landed.  (Sorry for the delay.)  Can you try to merge your feature addition onto the current master branch, e.g. via `git rebase` and resolving the conflict?

**Comment by j-lenoch** [comment]
Thank you very much, I'll take care of it!

**Comment by kevinbarabash** [comment]
@j-lenoch thanks for the PR.

**Pull request merged**
